### ISSUE TITLE
undefined symbol: _ZN11xercesc_3_211InputSource11setEncodingEPKDs

### ISSUE THREAD

**Issue by arkanoid87** [conda-forge/gdal-feedstock#264] opened 2019-02-01 07:33 UTC
Issue: 
undefined symbol: _ZN11xercesc_3_211InputSource11setEncodingEPKDs

CentOS Linux release 7.2.1511 (Core) + miniconda

<br/>
Environment (<code>conda list</code>):
<details>

```
# packages in environment at /home/nfs/jack/miniconda3/envs/jupyter:
#
# Name                    Version                   Build  Channel
absl-py                   0.6.1                 py36_1000    conda-forge
affine                    2.2.2                      py_0    conda-forge
altair                    2.3.0                 py36_1001    conda-forge
asn1crypto                0.24.0                py36_1003    conda-forge
astor                     0.7.1                      py_0    conda-forge
atk                       2.25.90              h05f3006_1    conda-forge
attrs                     18.2.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bcrypt                    3.1.4            py36h470a237_0    conda-forge
blas                      1.1                    openblas    conda-forge
bleach                    3.0.2                      py_1    conda-forge
blosc                     1.15.1               hfc679d8_0    conda-forge
bokeh                     1.0.2                 py36_1000    conda-forge
boost-cpp                 1.68.0               h3a22d5f_0    conda-forge
boto3                     1.9.70                     py_0    conda-forge
botocore                  1.12.70                    py_0    conda-forge
bottleneck                1.2.1            py36h7eb728f_1    conda-forge
branca                    0.3.1                      py_0    conda-forge
bzip2                     1.0.6                h470a237_2    conda-forge
c-ares                    1.15.0               h470a237_1    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
cairo                     1.14.12              h276e583_5    conda-forge
category_encoders         1.3.0                      py_0    conda-forge
certifi                   2018.11.29            py36_1000    conda-forge
cffi                      1.11.5           py36h5e8e0c9_1    conda-forge
cftime                    1.0.3.4          py36h7eb728f_0    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.0.4                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cloudpickle               0.6.1                      py_0    conda-forge
cryptography              2.3.1            py36hdffb7b8_0    conda-forge
cryptography-vectors      2.3.1                 py36_1000    conda-forge
curl                      7.63.0               h74213dd_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
cytoolz                   0.9.0.1          py36h470a237_1    conda-forge
dask                      1.1.1                      py_0    conda-forge
dask-core                 1.1.1                      py_0    conda-forge
dask-glm                  0.1.0                         0    conda-forge
dask-ml                   0.11.0                     py_0    conda-forge
dbus                      1.13.0               h3a4f0e9_0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
descartes                 1.1.0                      py_2    conda-forge
distributed               1.25.3                   py36_0    conda-forge
docutils                  0.14                  py36_1001    conda-forge
entrypoints               0.2.3                 py36_1002    conda-forge
expat                     2.2.5                hfc679d8_2    conda-forge
ffmpeg                    4.1                  h9db10b5_0    conda-forge
fiona                     1.8.4           py36h1c6dbfb_1002    conda-forge
folium                    0.7.0                      py_0    conda-forge
fontconfig                2.13.1               h65d0f4c_0    conda-forge
freetype                  2.9.1                h6debe1e_4    conda-forge
freexl                    1.0.5                h470a237_2    conda-forge
gast                      0.2.0                      py_0    conda-forge
gdal                      2.4.0           py36h1c6dbfb_1002    conda-forge
gdk-pixbuf                2.36.12              h4ab6910_1    conda-forge
geojson                   2.4.1                      py_0    conda-forge
geopandas                 0.4.0                      py_1    conda-forge
geos                      3.7.1             hf484d3e_1000    conda-forge
geotiff                   1.4.3                h9c44c65_0    conda-forge
gettext                   0.19.8.1             h5e8e0c9_1    conda-forge
giflib                    5.1.4                h470a237_1    conda-forge
glib                      2.56.2               h464dc38_1    conda-forge
gmp                       6.1.2                hfc679d8_0    conda-forge
gnutls                    3.6.5                ha0399c4_1    conda-forge
gobject-introspection     1.56.1           py36haaf12d0_1    conda-forge
graphite2                 1.3.13               hfc679d8_0    conda-forge
graphviz                  2.38.0               h08bfae6_9    conda-forge
grpcio                    1.16.0           py36hd60e7a3_0    conda-forge
gst-plugins-base          1.12.5               hde13a9d_0    conda-forge
gstreamer                 1.12.5               h5856ed1_0    conda-forge
gtk2                      2.24.31              hde048ef_0    conda-forge
h5netcdf                  0.6.2                      py_0    conda-forge
h5py                      2.9.0            py36he5c79e1_0    conda-forge
harfbuzz                  1.9.0                h04dbb29_1    conda-forge
hdf4                      4.2.13               h951d187_2    conda-forge
hdf5                      1.10.4          nompi_h5598ddc_1105    conda-forge
heapdict                  1.0.0                 py36_1000    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
idna                      2.8                   py36_1000    conda-forge
ipykernel                 5.1.0           py36h24bf2e0_1001    conda-forge
ipyleaflet                0.9.2                 py36_1001    conda-forge
ipympl                    0.2.1                 py36_1000    conda-forge
ipython                   7.2.0           py36h24bf2e0_1000    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.2                      py_0    conda-forge
jasper                    1.900.1              hff1ad4c_5    conda-forge
jedi                      0.13.2                py36_1000    conda-forge
jinja2                    2.10                       py_1    conda-forge
jmespath                  0.9.3                      py_1    conda-forge
jpeg                      9c                   h470a237_1    conda-forge
json-c                    0.13.1               h470a237_1    conda-forge
jsonschema                3.0.0a3               py36_1000    conda-forge
jupyter_client            5.2.4                      py_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterlab                0.35.4                   py36_0    conda-forge
jupyterlab_server         0.2.0                      py_0    conda-forge
kealib                    1.4.10               heffcb4b_2    conda-forge
keras                     2.2.4                    py36_0    conda-forge
keras-applications        1.0.4                      py_1    conda-forge
keras-preprocessing       1.0.2                      py_1    conda-forge
kiwisolver                1.0.1            py36h2d50403_2    conda-forge
krb5                      1.16.2               hbb41f41_0    conda-forge
libcurl                   7.63.0               hbdb9355_0    conda-forge
libdap4                   3.19.1               h8fe5423_1    conda-forge
libedit                   3.1.20170329         haf1bffa_1    conda-forge
libffi                    3.2.1                hfc679d8_5    conda-forge
libgcc-ng                 7.3.0                hdf63c60_0    conda-forge
libgdal                   2.4.0             h982c1cc_1002    conda-forge
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libgpuarray               0.7.6                h470a237_3    conda-forge
libiconv                  1.15                 h470a237_3    conda-forge
libkml                    1.3.0                he469717_9    conda-forge
libnetcdf                 4.6.2                h85b088c_1    conda-forge
libpng                    1.6.36               ha92aebf_0    conda-forge
libpq                     10.5                 he29860b_1    conda-forge
libprotobuf               3.6.1                hd28b015_0    conda-forge
libsodium                 1.0.16               h470a237_1    conda-forge
libspatialindex           1.8.5                hfc679d8_3    conda-forge
libspatialite             4.3.0a            hb5ec416_1026    conda-forge
libssh2                   1.8.0                h5b517e9_3    conda-forge
libstdcxx-ng              7.3.0                hdf63c60_0    conda-forge
libtiff                   4.0.10               he6b73bb_1    conda-forge
libtool                   2.4.6                h470a237_2    conda-forge
libuuid                   2.32.1               h470a237_2    conda-forge
libwebp                   1.0.1                h08eee79_0    conda-forge
libxcb                    1.13                 h470a237_2    conda-forge
libxml2                   2.9.8                h422b904_5    conda-forge
llvmlite                  0.26.0          py36hdbcaa40_1000    conda-forge
locket                    0.2.0                      py_2    conda-forge
lzo                       2.10                 h470a237_0    conda-forge
mako                      1.0.7                      py_1    conda-forge
markdown                  2.6.11                     py_0    conda-forge
markupsafe                1.1.0            py36h470a237_0    conda-forge
matplotlib                3.0.2                 py36_1002    conda-forge
matplotlib-base           3.0.2           py36h167e16e_1002    conda-forge
mistune                   0.8.4            py36h470a237_0    conda-forge
msgpack-python            0.6.0            py36h2d50403_0    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
munch                     2.3.2                      py_0    conda-forge
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1                  hfc679d8_2    conda-forge
netcdf4                   1.4.2            py36hf4e5497_1    conda-forge
nettle                    3.4.1                h470a237_2    conda-forge
nodejs                    11.9.0               hf484d3e_0    conda-forge
notebook                  5.7.4                 py36_1000    conda-forge
numba                     0.41.0          py36h637b7d7_1000    conda-forge
numexpr                   2.6.9            py36hf8a1672_0    conda-forge
numpy                     1.16.0          py36_blas_openblash1522bff_1000  [blas_openblas]  conda-forge
olefile                   0.46                       py_0    conda-forge
openblas                  0.3.3                ha44fe06_1    conda-forge
opencv                    3.4.4           py36_blas_openblash85ad109_1203  [blas_openblas]  conda-forge
openh264                  1.8.0                hd28b015_0    conda-forge
openjpeg                  2.3.0                h0e734dc_3    conda-forge
openssl                   1.0.2p            h14c3975_1002    conda-forge
packaging                 18.0                       py_0    conda-forge
pandas                    0.24.0           py36hf484d3e_0    conda-forge
pandoc                    2.5                           0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
pango                     1.40.14              he752989_2    conda-forge
paramiko                  2.4.2                 py36_1000    conda-forge
parso                     0.3.1                      py_0    conda-forge
partd                     0.3.9                      py_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.41                 hfc679d8_3    conda-forge
pexpect                   4.6.0                 py36_1000    conda-forge
pickleshare               0.7.5                 py36_1000    conda-forge
pillow                    5.3.0            py36hc736899_0    conda-forge
pip                       18.1                  py36_1000    conda-forge
pixman                    0.34.0               h470a237_3    conda-forge
plotly                    3.5.0                      py_0    conda-forge
poppler                   0.67.0               hdf8a1b3_2    conda-forge
poppler-data              0.4.9                         0    conda-forge
postgresql                10.5                 h66035e0_1    conda-forge
proj4                     5.2.0                h470a237_1    conda-forge
prometheus_client         0.5.0                      py_0    conda-forge
prompt_toolkit            2.0.7                      py_0    conda-forge
protobuf                  3.6.1            py36hfc679d8_1    conda-forge
psutil                    5.4.8            py36h470a237_0    conda-forge
psycopg2                  2.7.6.1          py36hdffb7b8_0    conda-forge
pthread-stubs             0.4                  h470a237_1    conda-forge
ptyprocess                0.6.0                 py36_1000    conda-forge
pyasn1                    0.4.4                      py_1    conda-forge
pycparser                 2.19                       py_0    conda-forge
pydot                     1.3.0                 py36_1000    conda-forge
pydotplus                 2.0.2                      py_2    conda-forge
pygments                  2.3.1                      py_0    conda-forge
pygpu                     0.7.6            py36h7eb728f_0    conda-forge
pynacl                    1.3.0           py36h14c3975_1000    conda-forge
pyopenssl                 18.0.0                py36_1000    conda-forge
pyparsing                 2.3.0                      py_0    conda-forge
pyproj                    1.9.5.1          py36h429999c_7    conda-forge
pyqt                      5.6.0            py36h8210e8a_8    conda-forge
pyrsistent                0.14.8           py36h470a237_0    conda-forge
pysal                     1.14.4.post2          py36_1001    conda-forge
pysocks                   1.6.8                 py36_1002    conda-forge
pytables                  3.4.4           py36h5d69a80_1004    conda-forge
python                    3.6.7             hd21baee_1001    conda-forge
python-chromedriver-binary 2.45.0                py36_1000    conda-forge
python-dateutil           2.7.5                      py_0    conda-forge
pytz                      2018.7                     py_0    conda-forge
pyyaml                    3.13             py36h470a237_1    conda-forge
pyzmq                     17.1.2           py36hae99301_1    conda-forge
qt                        5.6.2               h679f5bc_11    conda-forge
rasterio                  1.0.15           py36h286bbcc_0    conda-forge
readline                  7.0                  haf1bffa_1    conda-forge
requests                  2.21.0                py36_1000    conda-forge
retrying                  1.3.3                      py_2    conda-forge
rtree                     0.8.3                 py36_1000    conda-forge
s3transfer                0.1.13                py36_1001    conda-forge
scikit-learn              0.20.2          py36_blas_openblashebff5e3_1400  [blas_openblas]  conda-forge
scipy                     1.2.0           py36_blas_openblash1522bff_1201  [blas_openblas]  conda-forge
seaborn                   0.9.0                      py_0    conda-forge
selenium                  3.141.0          py36h470a237_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                40.6.3                   py36_0    conda-forge
shapely                   1.6.4           py36h092830f_1002    conda-forge
sip                       4.18.1           py36hfc679d8_0    conda-forge
six                       1.12.0                py36_1000    conda-forge
snuggs                    1.4.1                      py_1    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sqlalchemy                1.2.15           py36h470a237_0    conda-forge
sqlite                    3.26.0               hb1c47c0_0    conda-forge
statsmodels               0.9.0            py36h7eb728f_0    conda-forge
tblib                     1.3.2                      py_1    conda-forge
tensorboard               1.10.0                   py36_0    conda-forge
tensorflow                1.10.0                   py36_0    conda-forge
termcolor                 1.1.0                      py_2    conda-forge
terminado                 0.8.1                 py36_1001    conda-forge
testpath                  0.4.2                 py36_1000    conda-forge
theano                    1.0.3            py36hfc679d8_1    conda-forge
tk                        8.6.9                ha92aebf_0    conda-forge
toolchain                 2.3.0                         0    conda-forge
toolchain_c_linux-64      2.3.0                         0    conda-forge
toolchain_cxx_linux-64    2.3.0                         0    conda-forge
toolz                     0.9.0                      py_1    conda-forge
tornado                   5.1.1            py36h470a237_0    conda-forge
traitlets                 4.3.2                 py36_1000    conda-forge
traittypes                0.2.1                      py_1    conda-forge
urllib3                   1.24.1                py36_1000    conda-forge
vincent                   0.4.4                      py_1    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  0.14.1                     py_0    conda-forge
wheel                     0.32.3                   py36_0    conda-forge
widgetsnbextension        3.4.2                 py36_1000    conda-forge
x264                      1!152.20180717       h470a237_1    conda-forge
xarray                    0.10.9                   py36_0    conda-forge
xerces-c                  3.2.2                h5d6a6da_0    conda-forge
xorg-kbproto              1.0.7                h470a237_2    conda-forge
xorg-libice               1.0.9                h470a237_4    conda-forge
xorg-libsm                1.2.3                h8c8a85c_0    conda-forge
xorg-libx11               1.6.6                h470a237_0    conda-forge
xorg-libxau               1.0.8                h470a237_6    conda-forge
xorg-libxdmcp             1.1.2                h470a237_7    conda-forge
xorg-libxext              1.3.3                h470a237_4    conda-forge
xorg-libxpm               3.5.12               h470a237_2    conda-forge
xorg-libxrender           0.9.10               h470a237_2    conda-forge
xorg-libxt                1.1.5                h470a237_2    conda-forge
xorg-renderproto          0.11.1               h470a237_2    conda-forge
xorg-xextproto            7.3.0                h470a237_2    conda-forge
xorg-xproto               7.0.31               h470a237_7    conda-forge
xz                        5.2.4                h470a237_1    conda-forge
yaml                      0.1.7                h470a237_1    conda-forge
zeromq                    4.2.5                hfc679d8_6    conda-forge
zict                      0.1.3                      py_0    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```

     active environment : jupyter
    active env location : /home/nfs/jack/miniconda3/envs/jupyter
            shell level : 2
       user config file : /home/nfs/jack/.condarc
 populated config files : 
          conda version : 4.5.11
    conda-build version : not installed
         python version : 3.7.0.final.0
       base environment : /home/nfs/jack/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/nfs/jack/miniconda3/pkgs
                          /home/nfs/jack/.conda/pkgs
       envs directories : /home/nfs/jack/miniconda3/envs
                          /home/nfs/jack/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Linux/3.10.0-327.28.3.el7.x86_64 centos/7 glibc/2.17
                UID:GID : 1686200011:1686200011
             netrc file : None
           offline mode : False
```
</details>

<br/>

Same with gdal + libgdal 2.4.0, 2.3.3, 2.3.2
environment is installed with an environment.yml file:
<details>

```

name: jupyter
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.6
  - numpy
  - pandas
  - geopandas
  - geojson
  - pytables
  - jupyterlab
  - dask
  - dask-ml
  - paramiko
  - rasterio
  - scikit-learn
  - scipy
  - gdal
  - tensorflow
  - keras
  - altair
  - matplotlib
  - ipyleaflet
  - nodejs
  - ipympl
  - plotly
  - seaborn
  - folium
  - branca
  - category_encoders
  - opencv

```

</details>

<br/>

```
$ nm /home/nfs/jack/miniconda3/envs/jupyter/bin/../lib/libgdal.so.20 | grep _ZN11xercesc_3_211InputSource11setEncodingEPKDs
                 U _ZN11xercesc_3_211InputSource11setEncodingEPKDs
```

**Comment by arkanoid87** [comment] 2019-02-01 07:43
Update:

downgrading to gdal=2.2.4 works

2.4.0 KO
2.3.3 KO
2.3.2 KO
2.3.1 not tested (UnsatisfiableError in Solving Environment)
2.2.4 OK

**Comment by kmuehlbauer** [comment] 2019-02-01 09:46
Cant reproduce under linux using your env.yml. Newer packages are pulled in, though.

**Comment by arkanoid87** [comment] 2019-02-01 10:45
Do you confirm that the symbol

_ZN11xercesc_3_211InputSource11setEncodingEPKDs

is missing  in libgdal.so.20?

**Comment by kmuehlbauer** [comment] 2019-02-01 10:49
No, I can't confirm. In my fresh install using your env.yml this symbol is included.

**Comment by arkanoid87** [comment] 2019-02-01 10:58
I've downloaded the tar.bz2 package from anaconda.org on another machine

https://anaconda.org/conda-forge/libgdal/2.4.0/download/linux-64/libgdal-2.4.0-h982c1cc_1002.tar.bz2

and the symbol is undefined

```
➜  nm libgdal.so.20 | grep _ZN11xercesc_3_211InputSource11setEncodingEPKDs
                 U _ZN11xercesc_3_211InputSource11setEncodingEPKDs
```

**Comment by kmuehlbauer** [comment] 2019-02-01 11:18
@arkanoid87 Sorry, you are right, this symbol is undefined. I got missing and undefined mangled. 

Seems to come from Xerces-C.

**Comment by ocefpaf** [comment] 2019-03-14 10:57
The symbol mentioned above is missing but the library does not crash. Not sure why it is not there or why it should be but b/c the package is working I'm closing this. Please let me know if you are finding any problem using `gdal 2.4`.

**Closed by ocefpaf** 2019-03-14 10:57 UTC
