### ISSUE TITLE
osgeo/_gdal.so: undefined symbol: VSISupportsSparseFiles

### ISSUE THREAD

**Issue by snowman2** [conda-forge/gdal-feedstock#174] opened 2017-08-30 21:11 UTC
This occurred when building the GSSHApy package. 

URL to failed build: https://circleci.com/gh/conda-forge/gsshapy-feedstock/21

```
WARNING: conda-build appears to be out of date. You have version 2.1.17 but the
latest version is 3.0.14. Run

conda update -n root conda-build

to get the latest version.

+ source /opt/conda/bin/activate /feedstock_root/build_artefacts/gsshapy_1504109035575/_t_env
+ /feedstock_root/build_artefacts/gsshapy_1504109035575/_t_env/bin/python -s /feedstock_root/build_artefacts/gsshapy_1504109035575/test_tmp/run_test.py
import: 'gsshapy'
import: 'gsshapy.orm'
Traceback (most recent call last):
  File "/feedstock_root/build_artefacts/gsshapy_1504109035575/test_tmp/run_test.py", line 5, in <module>
    import gsshapy.orm
  File "/feedstock_root/build_artefacts/gsshapy_1504109035575/_t_env/lib/python2.7/site-packages/gsshapy/orm/__init__.py", line 22, in <module>
    from .prj import *
  File "/feedstock_root/build_artefacts/gsshapy_1504109035575/_t_env/lib/python2.7/site-packages/gsshapy/orm/prj.py", line 23, in <module>
    from osgeo import ogr, osr
  File "/feedstock_root/build_artefacts/gsshapy_1504109035575/_t_env/lib/python2.7/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/feedstock_root/build_artefacts/gsshapy_1504109035575/_t_env/lib/python2.7/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
ImportError: /feedstock_root/build_artefacts/gsshapy_1504109035575/_t_env/lib/python2.7/site-packages/osgeo/_gdal.so: undefined symbol: VSISupportsSparseFiles
TESTS FAILED: gsshapy-2.3.7-py27_0.tar.bz2
```

**Comment by ocefpaf** [comment] 2017-08-30 23:41
I am quite puzzled how conda can install `fiona`, which is pinned to `libgdal 2.1.*` along side `gdal 2.2.*` that explicitly requires `libgdal 2.2.*`. Anyways, I gave up trying to understand that and get the usual response... We need to "tricky" conda by requiring `gdal` instead of `libgdal` in `fiona`. (I am working on that.)

Meanwhile you can add a dummy requirement for `libgdal 2.1.*` in your recipe and ti should also work.

Closing this b/c it is not a `gdal` problem.

**Closed by ocefpaf** 2017-08-30 23:41 UTC

**Comment by snowman2** [comment] 2017-08-31 12:57
@ocefpaf, where would be the best place to post this issue?

**Comment by snowman2** [comment] 2017-08-31 12:58
Also, did you mean `libgdal 2.2.*`?

**Comment by ocefpaf** [comment] 2017-08-31 13:03
> Also, did you mean `libgdal 2.2.*`?

if you are referring to this comment:
```
Meanwhile you can add a dummy requirement for `libgdal 2.1.*` in your recipe and it should also work.
```

I meant `libgdal 2.1.*`. That is b/c `libgdal 2.2.*` would work with fiona and for some odd reason conda is putting inconsistent packages in the same env. 

> @ocefpaf, where would be the best place to post this issue?

Somewhere in the conda solver. But good luck getting their attention to this. You'll get the same answer we always got. The solver is perfect and you are using it wrong :unamused: 
(Sorry for the rant. Hopefully, when we move to `conda-build 3` these issue will be minimized b/c the pinning control is different there.)

**Comment by ocefpaf** [comment] 2017-08-31 13:08
BTW, latest `fiona` should work with `libgdal 2.2.*`. I just did not had the time to re-build it and re-pin everything yet. Should be done by the end of the week. That should help you there too.

**Comment by snowman2** [comment] 2017-08-31 13:10
That is frustrating! Thanks for getting back to me. I am trying out the solution in the gsshapy-feedstock now.

**Comment by snowman2** [comment] 2017-08-31 13:11
As a side note, for some reason it works on Windows and on Python 3.5 on OSX (https://travis-ci.org/conda-forge/gsshapy-feedstock/jobs/270057842).

**Comment by ocefpaf** [comment] 2017-08-31 13:22
> As a side note, for some reason it works on Windows and on Python 3.5 on OSX (https://travis-ci.org/conda-forge/gsshapy-feedstock/jobs/270057842).

Probably b/c the available packages for the solver are different.

The root of the issue is:

`fiona` is pinned `libgdal 2.1.*` but `conda` tries to be "smart" and installs latest version of everything it can, so you get `gdal 2.2.*` (some package there is requiring the python bindings) but `gdal 2.2.*` is, obviously, pinned to `libgdal 2.2.*` and `fiona`'s pin is ignored!

A proper solver would never break a pinning, specially if another option exists, like the option of using `gdal 2.1.*` in that build env. If that is not possible the pinning rule in the recipe should still never be broken, we should get an error message there instead.

(If you download that exactly `fiona` build number you'll see the pinning there.)

**Comment by snowman2** [comment] 2017-08-31 13:49
I just had to pin `gdal 2.1.*` and it worked for now. Thanks for helping!

**Comment by ebo** [comment] 2017-10-06 15:45
Just to complicate things a bit...  When I tried to update libgdal it tried to downgrade gdal.  The solution I found was to pin both gdal and libgdal (2.2.1)
