### ISSUE TITLE
gdal suggesting downgrade of libgdal

### ISSUE THREAD

**Issue by michaelaye** [conda-forge/gdal-feedstock#107] opened 2016-08-08 20:32 UTC
I just upgraded from OSX 10.10.5 to 10.11.6
Have gdal installed from conda default channel.
Was living without bleeding edge gdal for a while, waiting for conda-forge to sort it all out. ;)
Trying to install it now into a conda Python 3.5 environment that has (lib)/gdal 2.0.0 installed gives me currently this:
```bash
(stable) └─❱❱❱ conda install -c conda-forge gdal                   1 ⏎  +6237 14:23 ❰─┘
Using Anaconda API: https://api.anaconda.org
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /Users/klay6683/miniconda3/envs/stable:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    expat-2.1.0                |                1         105 KB  conda-forge
    giflib-5.1.2               |                1          70 KB  conda-forge
    icu-56.1                   |                4        22.0 MB  conda-forge
    jpeg-9b                    |                0         243 KB  conda-forge
    json-c-0.12                |                0          44 KB  conda-forge
    libgdal-1.11.2             |                1        12.8 MB
    libiconv-1.14              |                3         1.3 MB  conda-forge
    libuuid-1.0.3              |                1          12 KB  conda-forge
    proj.4-4.9.2               |                0         436 KB  conda-forge
    freexl-1.0.2               |                1          38 KB  conda-forge
    hdf5-1.8.17                |                2         3.4 MB  conda-forge
    libtiff-4.0.6              |                6         556 KB  conda-forge
    libxml2-2.9.3              |                9         1.9 MB  conda-forge
    postgresql-9.5.3           |                2         6.4 MB  conda-forge
    kealib-1.4.6               |                3         178 KB  conda-forge
    libdap4-3.18.0             |                2         2.7 MB  conda-forge
    libnetcdf-4.4.0            |                2         1.5 MB  conda-forge
    libspatialite-4.3.0a       |                9         2.1 MB  conda-forge
    openjpeg-2.1.0             |                6         203 KB  conda-forge
    gdal-2.1.1                 |      np111py35_1        17.9 MB  conda-forge
    pillow-3.2.0               |           py35_1         513 KB  conda-forge
    pytables-3.2.3.1           |      np111py35_0         1.7 MB
    ------------------------------------------------------------
                                           Total:        76.0 MB

The following NEW packages will be INSTALLED:

    expat:         2.1.0-1           conda-forge
    freexl:        1.0.2-1           conda-forge
    giflib:        5.1.2-1           conda-forge
    icu:           56.1-4            conda-forge
    json-c:        0.12-0            conda-forge
    libdap4:       3.18.0-2          conda-forge
    libiconv:      1.14-3            conda-forge
    libspatialite: 4.3.0a-9          conda-forge
    libuuid:       1.0.3-1           conda-forge
    libxml2:       2.9.3-9           conda-forge
    openjpeg:      2.1.0-6           conda-forge
    postgresql:    9.5.3-2           conda-forge
    proj.4:        4.9.2-0           conda-forge

The following packages will be UPDATED:

    gdal:          2.0.0-np111py35_3             --> 2.1.1-np111py35_1   conda-forge
    hdf5:          1.8.16-0                      --> 1.8.17-2            conda-forge
    jpeg:          8d-1                          --> 9b-0                conda-forge
    kealib:        1.4.5-2                       --> 1.4.6-3             conda-forge
    libnetcdf:     4.4.0-1                       --> 4.4.0-2             conda-forge
    libtiff:       4.0.6-2                       --> 4.0.6-6             conda-forge
    pytables:      3.2.2-np111py35_4             --> 3.2.3.1-np111py35_0

The following packages will be SUPERCEDED by a higher-priority channel:

    pillow:        3.3.0-py35_0                  --> 3.2.0-py35_1        conda-forge

The following packages will be DOWNGRADED due to dependency conflicts:

    libgdal:       2.0.0-4                       --> 1.11.2-1

Proceed ([y]/n)?
```
As you can see, it suggests to downgrade pillow from 3.3.0 to 3.2.0, but weirdly, it wants to downgrade libgdal 2.0.0 to 1.11.2, even so it wants to install gdal 2.1.1 with it? Isn't that wrong?

**Comment by ocefpaf** [comment] 2016-08-08 20:39
It is hard to know what packages conda is trying to honor there. So let's isolate this into an env in order to debug. First do a `conda update --all` to get the latest version of `conda`. Then check if `conda-forge` is added on top of `defaults` in your `.condarc` file.That is b/c latest `conda` has the notion of channel preference and the channel that goes on top is the main one. Then do:

```shell
conda create --yes -n TEST python=3.5 gdal -c conda-forge
source activate TEST
python -c "import gdal"  # Just to check if things work.
conda info > debug.txt
conda list >> debug.txt
```

And send attached `debug.txt` here.

BTW I can tell that you are honoring some other package because on `conda-forge` we do not have `gdal` and `libgdal`. It is only one package named `gdal`.

**Comment by michaelaye** [comment] 2016-08-08 21:20
your way of testing would cover up the update problem, so I did this:
```bash
conda create --yes -n TEST python=3.5 gdal
source activate TEST
python -c "import gdal"
conda info > debug.txt
conda list >> debug.txt
```
(attached)
[debug.txt](https://github.com/conda-forge/gdal-feedstock/files/407763/debug.txt)

First question I already have is why my `stable` env stays on gdal 2.0.0 even when I do `conda update gdal`?

Now, in `TEST`, I did a `conda search --reverse-dependency libgdal`, and only gdal, fiona and rasterio demand it. I only have `gdal` installed in this test environment though.

When I now just do `conda install -c conda-forge gdal`, it again wants to downgrade libgdal, which means, this comes from conda-forge somehow:
```bash
(TEST) └─❱❱❱ conda install -c conda-forge gdal                          +6264 15:20 ❰─┘
Using Anaconda API: https://api.anaconda.org
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /Users/klay6683/miniconda3/envs/TEST:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libgdal-1.11.2             |                1        12.8 MB

The following NEW packages will be INSTALLED:

    expat:         2.1.0-1      conda-forge
    freexl:        1.0.2-1      conda-forge
    giflib:        5.1.2-1      conda-forge
    icu:           56.1-4       conda-forge
    json-c:        0.12-0       conda-forge
    libdap4:       3.18.0-2     conda-forge
    libiconv:      1.14-3       conda-forge
    libpng:        1.6.23-0     conda-forge
    libspatialite: 4.3.0a-9     conda-forge
    libuuid:       1.0.3-1      conda-forge
    libxml2:       2.9.3-9      conda-forge
    openjpeg:      2.1.0-6      conda-forge
    postgresql:    9.5.3-2      conda-forge
    proj.4:        4.9.2-0      conda-forge

The following packages will be UPDATED:

    gdal:          2.1.0-py35_0             --> 2.1.1-np111py35_1 conda-forge
    jpeg:          8d-1                     --> 9b-0              conda-forge
    libtiff:       4.0.6-2                  --> 4.0.6-6           conda-forge

The following packages will be SUPERCEDED by a higher-priority channel:

    geos:          3.5.0-0                  --> 3.4.2-2           conda-forge
    hdf4:          4.2.12-0                 --> 4.2.11-4          conda-forge

The following packages will be DOWNGRADED due to dependency conflicts:

    libgdal:       2.1.0-0                  --> 1.11.2-1
```

**Comment by ocefpaf** [comment] 2016-08-09 00:48
> I did not add conda-forge as a channel:

Hence the problems you are having. You are mixing packages and resolutions that the `conda` solver cannot do for you without the channel. See things like: 

`gdal:          2.1.0-py35_0             --> 2.1.1-np111py35_1 conda-forge`

`conda-forge` has a `numpy` build string and `defaults` does not. That is one of the many things where the conda solver is choking.

**Comment by michaelaye** [comment] 2016-08-09 21:41
Hm, I added conda-forge, and a `conda update gdal` provides the exact same response as above, if my eyes are not bad (in fact they are bad today, so I might miss something):

```bash
┌─( ~ )─────────────────────────────────────────────────────────────────────────────────────────( @macd2860 )─┐
(TEST) └─❱❱❱ cat ~/.condarc                                                                1 ⏎  +6323 15:39 ❰─┘
channels:
  - conda-forge
  - defaults

┌─( ~ )─────────────────────────────────────────────────────────────────────────────────────────( @macd2860 )─┐
(TEST) └─❱❱❱ conda update gdal                                                                  +6324 15:40 ❰─┘
Using Anaconda API: https://api.anaconda.org
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /Users/klay6683/miniconda3/envs/TEST:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libgdal-1.11.2             |                1        12.8 MB

The following NEW packages will be INSTALLED:

    expat:         2.1.0-1      conda-forge
    freexl:        1.0.2-1      conda-forge
    giflib:        5.1.2-1      conda-forge
    icu:           56.1-4       conda-forge
    json-c:        0.12-0       conda-forge
    libdap4:       3.18.0-2     conda-forge
    libiconv:      1.14-3       conda-forge
    libpng:        1.6.23-0     conda-forge
    libspatialite: 4.3.0a-9     conda-forge
    libuuid:       1.0.3-1      conda-forge
    libxml2:       2.9.3-9      conda-forge
    openjpeg:      2.1.0-6      conda-forge
    postgresql:    9.5.3-2      conda-forge
    proj.4:        4.9.2-0      conda-forge

The following packages will be UPDATED:

    gdal:          2.1.0-py35_0             --> 2.1.1-np111py35_1 conda-forge
    jpeg:          8d-1                     --> 9b-0              conda-forge
    libtiff:       4.0.6-2                  --> 4.0.6-6           conda-forge

The following packages will be SUPERCEDED by a higher-priority channel:

    geos:          3.5.0-0                  --> 3.4.2-2           conda-forge
    hdf4:          4.2.12-0                 --> 4.2.11-4          conda-forge

The following packages will be DOWNGRADED due to dependency conflicts:

    libgdal:       2.1.0-0                  --> 1.11.2-1

Proceed ([y]/n)? n
```

**Comment by michaelaye** [comment] 2016-08-09 21:55
it's almost like `conda` tries to get rid of `libgdal` (as it's not required by the gdal of conda-forge anymore), and doesn't know how and then downgrades it?

**Comment by ocefpaf** [comment] 2016-08-10 12:28
> it's almost like `conda` tries to get rid of `libgdal` (as it's not required by the gdal of conda-forge anymore), and doesn't know how and then downgrades it?

Could be... Not sure what is in the cards for `gdal` in `defaults` but as you can see from https://github.com/conda-forge/gdal-feedstock/issues/95 we are unable to communicate with them in that regard.

However, I cannot reproduce that error in a fresh install unless I install force `libgdal`.

**Comment by michaelaye** [comment] 2016-08-10 17:19
Hm, that would be mysterious. Are you sure you did as first command `conda create --yes -n TEST python=3.5 gdal' like I did, and not as you suggested `conda create  --yes -n TEST python=3.5 gdal -c conda-forge`? As I argued above, your way disguises the update problem of conda.

**Comment by ocefpaf** [comment] 2016-08-10 17:22
> As I argued above, your way disguises the update problem of conda.

"My way" enforces the right channel. If you do not issue the command that way you are bound to get the `defaults`.

Closing this as there is nothing we can do on `conda-forge`. If you have any suggestion on how to improve conda channels handling you can open new issues on the `conda` repo.

**Closed by ocefpaf** 2016-08-10 17:22 UTC

**Comment by michaelaye** [comment] 2016-08-10 17:24
I'm not sure that's a truthful statement, as a split of gdal into gdal/libgdal would indeed remedy this situation. So it's not true that the gdal-feedstock can't do anything about this. You stated in #95 that you don't like to break people's environments, but as long as ppl do start with the defaults channel and then want to upgrade to conda-forge, while not really a break, it is dirty, as it leaves old cruft lying around that potentially could cause confusion.
