### ISSUE TITLE
Remove the need for the GDAL_DATA environment variable

### ISSUE THREAD

**Issue by pelson** [conda-forge/gdal-feedstock#35] opened 2016-04-14 06:04 UTC
It is causing us to have to [workaround](https://github.com/conda-forge/staged-recipes/pull/159/files#r59058552) the problem elsewhere, and would be nice to avoid if possible (even if it means a patch).

Not a huge priority, but it would be helpful to keep a list of places that the GDAL_DATA information has leaked out of this feedstock:

 * https://github.com/conda-forge/staged-recipes/pull/159/files#r59058552

**Comment by gillins** [comment] 2016-04-14 07:07
Do we know why this isn't set in the _test environment? Should it be fixed in conda instead?
There must be other packages that have the same problem (ie requiring an environment variable to be set).

**Comment by ocefpaf** [comment] 2016-04-14 10:22
> Do we know why this isn't set in the _test environment? Should it be fixed in conda instead?

I just checked a fresh install and I notice that we have a bug

```shell
conda create --name GDAL --channel conda-forge python=2.7 gdal=1.11.4
source activate GDAL
echo $GDAL_DATA
/home/filipe/miniconda/pkgs/libgdal-2.0.0-0/share/gdal
```

That directory does not exist. I will take a closer look at this.

**Comment by gillins** [comment] 2016-04-15 05:52
Seems fine for me. Do you have $GDAL_DATA set outside of Conda? The activate script won't change it if you have (perhaps it should?).

**Comment by ocefpaf** [comment] 2016-04-15 10:50
> Do you have $GDAL_DATA set outside of Conda? 

Nope. As you can see installed `gdal=1.11.4`, but the env var is pointing to `libgdal-2.0.0`.

**Comment by gillins** [comment] 2016-04-16 06:00
On my machine I get a different result:
`conda create --name GDAL1 --channel conda-forge python=3.5 gdal=1.11.4
source activate GDAL1
echo $GDAL_DATA
/home/sam/miniconda3/envs/GDAL1/etc/conda/activate.d/../../../share/gdal
conda create --name GDAL2 --channel conda-forge python=3.5 gdal=2.0.2
source activate GDAL2
echo $GDAL_DATA
/home/sam/miniconda3/envs/GDAL2/etc/conda/activate.d/../../../share/gdal
`

Which seems correct, so that's why I was wondering if you had $GDAL_DATA set elsewhere maybe in your ~/.bashrc?

**Comment by ocefpaf** [comment] 2016-04-16 18:25
> Which seems correct, so that's why I was wondering if you had $GDAL_DATA set elsewhere maybe in your ~/.bashrc?

I was going to answer: I never set variables in my `~/.zshrc`! But it seems that I forgot this

```shell
export GDAL_DATA=$HOME/miniconda/pkgs/libgdal-2.0.0-0/share/gdal
```

since last SciPy and the geo-processing tutorial!

So... Sorry :flushed: 

@pelson I guess `GDAL` is OK setting the env var. The problem is really conda and the `_test` env.

**Closed by ocefpaf** 2016-04-16 18:25 UTC
