### ISSUE TITLE
LERC Compression support in conda-forge builds?

### ISSUE THREAD

**Issue by adriancaruana** [conda-forge/gdal-feedstock#381] opened 2020-04-23 04:51 UTC
Issue:

I've been trying to use `LERC` compression with the `'GTiff'` Driver in `gdal`, however, when doing so these GeoTiffs are being written to disk raw-uncompressed. When using `gdal_translate` with `-co COMPRESS=LERC`, I get the following output:
```
Warning 6: 'LERC' is an unexpected value for COMPRESS creation option of type string-select.
Warning 6: driver GTiff does not support creation option MAX_Z_ERROR
Warning 5: COMPRESS=LERC value not recognised, ignoring.
```

I have tried using [osgeo/gdal:ubuntu-full-3.0.3](https://hub.docker.com/layers/osgeo/gdal/ubuntu-full-3.0.3/images/sha256-386131d5168fcbd9242aa7068d3651c4a77ab18a8d9e4456df35a3571df0503b?context=explore), which successfully writes LERC compressed GeoTiffs to disk with the same `gdal_translate` commands on the same input datasets I tried above. 

**Q: Is LERC compression enabled in the `conda-forge` builds?**

<br/>
Environment (<code>conda list</code>):
<details>

```
conda list | grep gdal
gdal                      3.0.4            py37h4b180d9_3    conda-forge
libgdal                   3.0.4                h94bbfbd_3    conda-forge
```
Full:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
absl-py                   0.9.0            py37hc8dfbb8_1    conda-forge
affine                    2.3.0                      py_0    conda-forge
alembic                   1.3.3                      py_0    conda-forge
astor                     0.7.1                      py_0    conda-forge
astroid                   2.3.3                    py37_1    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     19.3.0                     py_0    conda-forge
aws-adfs                  1.24.3                   pypi_0    pypi
awscli                    1.18.32          py37hc8dfbb8_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
beautifulsoup4            4.8.2                    py37_0    conda-forge
binutils_impl_linux-64    2.34                 h53a641e_0    conda-forge
binutils_linux-64         2.34                hc952b39_18    conda-forge
blas                      2.14                   openblas    conda-forge
bleach                    3.1.0                      py_0    conda-forge
blinker                   1.4                        py_1    conda-forge
blosc                     1.17.1               he1b5a44_0    conda-forge
bokeh                     1.4.0                    py37_0    conda-forge
boost-cpp                 1.72.0               h8e57a91_0    conda-forge
boto3                     1.12.32            pyh9f0ad1d_0    conda-forge
botocore                  1.15.32            pyh9f0ad1d_0    conda-forge
branca                    0.4.0                      py_0    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
c-ares                    1.15.0            h516909a_1001    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
cachetools                4.0.0                    pypi_0    pypi
cairo                     1.16.0            hcf35c78_1003    conda-forge
certifi                   2019.11.28       py37hc8dfbb8_1    conda-forge
certipy                   0.1.3                      py_0    conda-forge
cffi                      1.13.2           py37h8022711_0    conda-forge
cfitsio                   3.470                hb60a0a2_2    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cloudpickle               1.2.2                      py_1    conda-forge
colorama                  0.4.3                      py_0    conda-forge
conda                     4.8.2                    py37_0    conda-forge
conda-build               3.18.11                  py37_0    conda-forge
conda-package-handling    1.6.0            py37h516909a_1    conda-forge
configparser              5.0.0                    pypi_0    pypi
configurable-http-proxy   4.2.0           node13_he01fd0c_2    conda-forge
cryptography              2.8              py37h72c5cf5_1    conda-forge
curl                      7.65.3               hf8cf82a_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.14          py37he1b5a44_0    conda-forge
cytoolz                   0.10.1           py37h516909a_0    conda-forge
dask                      2.9.2                      py_0    conda-forge
dask-core                 2.9.2                      py_0    conda-forge
datadog                   0.35.0                     py_0    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.1                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
descartes                 1.1.0                      py_4    conda-forge
dill                      0.3.1.1                  py37_0    conda-forge
distributed               2.10.0                     py_0    conda-forge
docutils                  0.15.2                   py37_0    conda-forge
embree                    2.14.0                        0    conda-forge
entrypoints               0.3                   py37_1000    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
fastcache                 1.1.0            py37h516909a_0    conda-forge
ffmpeg                    4.1.3                h167e202_0    conda-forge
fido2                     0.8.1                    pypi_0    pypi
filelock                  3.0.10                     py_0    conda-forge
fiona                     1.8.13           py37h900e953_0    conda-forge
folium                    0.10.1                     py_0    conda-forge
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
freexl                    1.0.5             h14c3975_1002    conda-forge
fsspec                    0.6.2                      py_0    conda-forge
furl                      2.1.0                      py_0    conda-forge
gast                      0.2.2                    pypi_0    pypi
gcc_impl_linux-64         7.3.0                hd420e75_5    conda-forge
gcc_linux-64              7.3.0               h553295d_18    conda-forge
gdal                      3.0.4            py37h4b180d9_3    conda-forge
geographiclib             1.50                       py_0    conda-forge
geojson                   2.5.0                      py_0    conda-forge
geopandas                 0.7.0                      py_1    conda-forge
geopy                     1.21.0                     py_0    conda-forge
geos                      3.8.1                he1b5a44_0    conda-forge
geotiff                   1.5.1                hcbe54f9_9    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
gevent                    1.4.0            py37h516909a_0    conda-forge
giflib                    5.2.1                h516909a_2    conda-forge
glib                      2.58.3          py37he00f558_1003    conda-forge
glob2                     0.7                        py_0    conda-forge
gmp                       6.2.0                he1b5a44_0    conda-forge
gmpy2                     2.1.0b1          py37h04dde30_0    conda-forge
gnutls                    3.6.5             hd3a4fd2_1002    conda-forge
google-auth               1.12.0                   pypi_0    pypi
google-auth-oauthlib      0.4.1                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
graphite2                 1.3.13            he1b5a44_1001    conda-forge
greenlet                  0.4.15           py37h8f50634_1    conda-forge
grpcio                    1.23.0           py37hb0870dc_1    conda-forge
gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
gstreamer                 1.14.5               h36ae1b5_2    conda-forge
gxx_impl_linux-64         7.3.0                hdf63c60_5    conda-forge
gxx_linux-64              7.3.0               h553295d_18    conda-forge
h5py                      2.10.0          nompi_py37h513d04c_102    conda-forge
harfbuzz                  2.4.0                h9f30f68_3    conda-forge
hdf4                      4.2.13            hf30be14_1003    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
horovod                   0.19.1                   pypi_0    pypi
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.8                   py37_1000    conda-forge
imagecodecs-lite          2019.12.3        py37h8f50634_0    conda-forge
imageio                   2.8.0                      py_0    conda-forge
importlib_metadata        1.5.0                    py37_0    conda-forge
inflect                   4.0.0                    py37_1    conda-forge
ipykernel                 5.1.4            py37h5ca1d4c_0    conda-forge
ipython                   7.11.1           py37h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
isort                     4.3.21           py37hc8dfbb8_1    conda-forge
jaraco.itertools          5.0.0                      py_0    conda-forge
jasper                    1.900.1           h07fcdf6_1006    conda-forge
jedi                      0.16.0                   py37_0    conda-forge
jinja2                    2.11.0                     py_0    conda-forge
jmespath                  0.9.5                      py_0    conda-forge
joblib                    0.14.1                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
json-c                    0.13.1            h14c3975_1001    conda-forge
json5                     0.8.5                      py_0    conda-forge
jsonschema                3.2.0                    py37_0    conda-forge
jupyter_client            5.3.4                    py37_1    conda-forge
jupyter_contrib_core      0.3.3                      py_2    conda-forge
jupyter_contrib_nbextensions 0.5.1                    py37_0    conda-forge
jupyter_core              4.6.1                    py37_0    conda-forge
jupyter_highlight_selected_word 0.2.0                 py37_1000    conda-forge
jupyter_latex_envs        1.4.6                 py37_1000    conda-forge
jupyter_nbextensions_configurator 0.4.1                    py37_0    conda-forge
jupyter_telemetry         0.0.4                      py_0    conda-forge
jupyterhub                1.1.0                    py37_2    conda-forge
jupyterhub-base           1.1.0                    py37_2    conda-forge
jupyterlab                1.2.5              pyhf63ae98_0    defaults
jupyterlab_server         1.0.6                      py_0    conda-forge
kealib                    1.4.12               hec59c27_0    conda-forge
keras                     2.3.1                    py37_0    conda-forge
keras-applications        1.0.8                      py_1    conda-forge
keras-preprocessing       1.1.0                      py_0    conda-forge
kiwisolver                1.1.0            py37hc9558a2_0    conda-forge
krb5                      1.16.4               h2fd8d38_0    conda-forge
lame                      3.100             h14c3975_1001    conda-forge
lazy-object-proxy         1.4.3            py37h8f50634_2    conda-forge
ld_impl_linux-64          2.34                 h53a641e_0    conda-forge
lerc                      0.1.0                    pypi_0    pypi
libarchive                3.3.3             hc47fbbf_1007    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libclang                  9.0.1           default_hde54327_0    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libdap4                   3.20.4               hd3bb157_0    conda-forge
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgdal                   3.0.4                h94bbfbd_3    conda-forge
libgfortran-ng            7.3.0                hdf63c60_4    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libgpuarray               0.7.6             h14c3975_1003    conda-forge
libiconv                  1.15              h516909a_1006    conda-forge
libkml                    1.3.0             hb574062_1011    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
liblapacke                3.8.0               14_openblas    conda-forge
liblief                   0.9.0                hf8a498c_1    conda-forge
libllvm8                  8.0.1                hc9558a2_0    conda-forge
libllvm9                  9.0.1                hc9558a2_0    conda-forge
libnetcdf                 4.7.4           nompi_h9f9fd6a_101    conda-forge
libopenblas               0.3.7                h5ec1e0e_6    conda-forge
libopencv                 4.2.0                    py37_3    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libpq                     12.2                 hae5116b_0    conda-forge
libprotobuf               3.11.2               h8b12597_0    conda-forge
libsodium                 1.0.17               h516909a_0    conda-forge
libspatialindex           1.9.3                he1b5a44_3    conda-forge
libspatialite             4.3.0a            heb269f5_1037    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libtiff                   4.1.0                hc3755c2_3    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libuv                     1.34.0               h516909a_0    conda-forge
libwebp                   1.0.2                h56121f0_5    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxkbcommon              0.10.0               he1b5a44_0    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
libxslt                   1.1.33               h31b3aaa_0    conda-forge
llvmlite                  0.31.0           py37h8b12597_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.5.0            py37he3881c9_1    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
lzo                       2.10              h14c3975_1000    conda-forge
mako                      1.1.0                      py_0    conda-forge
markdown                  3.2.1                      py_0    conda-forge
markupsafe                1.1.1            py37h516909a_0    conda-forge
matplotlib                3.1.2                    py37_1    conda-forge
matplotlib-base           3.1.2            py37h250f245_1    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
memory_profiler           0.57.0                     py_0    conda-forge
mistune                   0.8.4           py37h516909a_1000    conda-forge
mizani                    0.6.0                      py_0    conda-forge
mock                      3.0.5            py37hc8dfbb8_1    conda-forge
more-itertools            8.2.0                      py_0    conda-forge
mpc                       1.1.0             h04dde30_1006    conda-forge
mpfr                      4.0.2                he80fd80_0    conda-forge
mpmath                    1.1.0                      py_0    conda-forge
msgpack-python            0.6.2            py37hc9558a2_0    conda-forge
munch                     2.5.0                      py_0    conda-forge
nb_conda                  2.2.1                    py37_2    conda-forge
nb_conda_kernels          2.2.3                    py37_0    conda-forge
nbconvert                 5.6.1                    py37_0    conda-forge
nbformat                  5.0.4                      py_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
nettle                    3.4.1             h1bed415_1002    conda-forge
networkx                  2.4                        py_0    conda-forge
nodejs                    13.7.0               h10a4023_0    conda-forge
notebook                  6.0.3                    py37_0    conda-forge
nspr                      4.25                 he1b5a44_0    conda-forge
nss                       3.47                 he751ad9_0    conda-forge
numba                     0.48.0           py37hb3f55d8_0    conda-forge
numexpr                   2.7.1            py37hb3f55d8_0    conda-forge
numpy                     1.17.5           py37h95a1406_0    conda-forge
nvidia-ml-py3             7.352.0                  pypi_0    pypi
oauthlib                  3.0.1                      py_0    conda-forge
olefile                   0.46                       py_0    conda-forge
opencv                    4.2.0                    py37_3    conda-forge
openh264                  1.8.0             hdbcaa40_1000    conda-forge
openjpeg                  2.3.1                h981e76c_3    conda-forge
openssl                   1.1.1f               h516909a_0    conda-forge
opt-einsum                3.2.0                    pypi_0    pypi
orderedmultidict          1.0.1                      py_0    conda-forge
packaging                 20.1                       py_0    conda-forge
palettable                3.3.0                      py_0    conda-forge
pamela                    1.0.0                      py_0    conda-forge
pandas                    1.0.3            py37h0da4684_0    conda-forge
pandoc                    2.9.1.1                       0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.6.0                      py_0    conda-forge
partd                     1.1.0                      py_0    conda-forge
patchelf                  0.10                 he1b5a44_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pexpect                   4.8.0                    py37_0    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pillow                    7.0.0            py37hefe7db6_0    conda-forge
pip                       20.0.2                   py37_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
pkg-config                0.29.2            h516909a_1006    conda-forge
pkginfo                   1.5.0.1                    py_0    conda-forge
plotnine                  0.6.0                      py_0    conda-forge
pluggy                    0.13.0                   py37_0    conda-forge
poppler                   0.67.0               h14e79db_8    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                12.2                 hf1211e9_0    conda-forge
progressbar2              3.50.0                     py_2    conda-forge
proj                      6.3.1                hc80f0dc_1    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            3.0.3                      py_0    conda-forge
protobuf                  3.11.2           py37he1b5a44_0    conda-forge
psutil                    5.6.7            py37h516909a_0    conda-forge
psycopg2                  2.8.4            py37h72c5cf5_1    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py                        1.8.1                      py_0    conda-forge
py-lief                   0.9.0            py37he1b5a44_1    conda-forge
py-opencv                 4.2.0            py37h43977f1_3    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.8                    pypi_0    pypi
pycocotools               2.0                      pypi_0    pypi
pycosat                   0.6.3           py37h516909a_1002    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pycurl                    7.43.0.4         py37h16ce93b_0    conda-forge
pyembree                  0.1.6            py37h0da4684_1    conda-forge
pygments                  2.5.2                      py_0    conda-forge
pygpu                     0.7.6           py37hc1659b7_1000    conda-forge
pyjwt                     1.7.1                      py_0    conda-forge
pykerberos                1.2.1                    pypi_0    pypi
pylint                    2.4.4                    py37_0    conda-forge
pylint-fail-under         0.3.0                    pypi_0    pypi
pyopenssl                 19.1.0                   py37_0    conda-forge
pyparsing                 2.4.6                      py_0    conda-forge
pyproj                    2.6.0            py37heba2c01_0    conda-forge
pyqt                      5.12.3           py37hcca6a23_1    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.15.7           py37h516909a_0    conda-forge
pyshp                     2.1.0                      py_0    conda-forge
pysocks                   1.7.1                    py37_0    conda-forge
pytables                  3.6.1            py37h9f153d1_1    conda-forge
pytest                    5.4.1            py37hc8dfbb8_0    conda-forge
python                    3.7.6           h8356626_5_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-dotenv             0.12.0                     py_0    conda-forge
python-editor             1.0.4                      py_0    conda-forge
python-json-logger        0.1.11                     py_0    conda-forge
python-libarchive-c       2.9                      py37_0    conda-forge
python-utils              2.4.0                      py_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2019.3                     py_0    conda-forge
pywavelets                1.1.1            py37hc1659b7_0    conda-forge
pyyaml                    5.3              py37h516909a_0    conda-forge
pyzmq                     18.1.1           py37h1768529_0    conda-forge
qt                        5.12.5               hd8c4c69_1    conda-forge
rasterio                  1.1.3            py37h900e953_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.23.0             pyh8c360ce_2    conda-forge
requests-kerberos         0.12.0                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
retrying                  1.3.3                      py_2    conda-forge
ripgrep                   12.0.1               h516909a_0    conda-forge
rsa                       3.4.2                      py_1    conda-forge
rtree                     0.9.4            py37h8526d28_1    conda-forge
ruamel.yaml               0.16.6           py37h516909a_0    conda-forge
ruamel.yaml.clib          0.2.0            py37h516909a_0    conda-forge
ruamel_yaml               0.15.80         py37h516909a_1000    conda-forge
s3transfer                0.3.3            py37hc8dfbb8_0    conda-forge
scikit-image              0.16.2           py37hb3f55d8_0    conda-forge
scikit-learn              0.22.1           py37hcdab131_1    conda-forge
scipy                     1.4.1            py37ha3d9a3c_2    conda-forge
seaborn                   0.9.0                      py_2    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                45.1.0                   py37_0    conda-forge
shapely                   1.7.0            py37hc88ce51_2    conda-forge
simplejson                3.17.0           py37h516909a_0    conda-forge
six                       1.14.0                   py37_0    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
soupsieve                 1.9.4                    py37_0    conda-forge
sqlalchemy                1.3.15           py37h8f50634_1    conda-forge
sqlite                    3.30.1               h7b6447c_0    defaults
statsmodels               0.11.0           py37h516909a_0    conda-forge
sympy                     1.5.1                    py37_1    conda-forge
tbb                       2018.0.5             h2d50403_0    conda-forge
tblib                     1.6.0                      py_0    conda-forge
tensorboard               2.1.1                    pypi_0    pypi
tensorflow                2.1.0                    pypi_0    pypi
tensorflow-estimator      2.1.0                    pypi_0    pypi
tensorflow-gpu            2.1.0                    pypi_0    pypi
tensorflow-serving-api    2.1.0                    pypi_0    pypi
tensorflow-serving-api-gpu 2.1.0                    pypi_0    pypi
tensorlayer               2.2.1                    pypi_0    pypi
termcolor                 1.1.0                      py_2    conda-forge
terminado                 0.8.3                    py37_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
theano                    1.0.4           py37he1b5a44_1001    conda-forge
tifffile                  2020.2.16                  py_0    conda-forge
tiledb                    1.7.0                hcde45ca_2    conda-forge
tini                      0.18.0            h14c3975_1001    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.3            py37h516909a_0    conda-forge
tqdm                      4.44.1             pyh9f0ad1d_0    conda-forge
traitlets                 4.3.3                    py37_0    conda-forge
trimesh                   3.6.18             pyh9f0ad1d_0    conda-forge
typed-ast                 1.4.1            py37h516909a_0    conda-forge
tzcode                    2019a             h516909a_1002    conda-forge
unzip                     6.0                  h516909a_0    conda-forge
urllib3                   1.25.7                   py37_0    conda-forge
vincent                   0.4.4                      py_1    conda-forge
wcwidth                   0.1.8                      py_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  1.0.0                      py_0    conda-forge
wheel                     0.34.1                   py37_0    conda-forge
widgetsnbextension        3.5.1                    py37_0    conda-forge
wrapt                     1.12.1           py37h8f50634_1    conda-forge
x264                      1!152.20180806       h14c3975_0    conda-forge
xerces-c                  3.2.2             h8412b87_1004    conda-forge
xlrd                      1.2.0                      py_0    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.2.2                h516909a_1    conda-forge
zeromq                    4.3.2                he1b5a44_2    conda-forge
zict                      1.0.0                      py_0    conda-forge
zipp                      2.1.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.4                h3b9ef0a_1    conda-forge
```

</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : None
       user config file : /home/jovyan/.condarc
 populated config files : /opt/conda/.condarc
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __cuda=10.2
                          __glibc=2.27
       base environment : /opt/conda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /home/jovyan/.conda/pkgs
       envs directories : /opt/conda/envs
                          /home/jovyan/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.2 requests/2.23.0 CPython/3.7.6 Linux/5.3.0-45-generic ubuntu/18.04.3 glibc/2.27
                UID:GID : 1314607273:1314600513
             netrc file : None
           offline mode : False
```
</details>

**Comment by kmuehlbauer** [comment] 2020-04-23 05:08
@adriancaruana Reading from the [gdal docs](https://gdal.org/drivers/raster/cog.html?highlight=lerc#general-creation-options) about LERC it seems only supported if internal libtiff is enabled for gdal. `conda-forge` gdal uses external libtiff, So this might not work out of the box.

Please ask on osgeo/gdal or gdal-dev list or @rouault might chime in with some guidance (much appreciated) on how to tackle this.

**Comment by adriancaruana** [comment] 2020-04-23 05:23
Thanks @kmuehlbauer , I was unaware that `conda-forge` used external `libtiff`. Will chime in on `osgeo/gdal`. @rouault if you could advise that would be great.

**Comment by rouault** [comment] 2020-04-23 09:20
yes, the LERC codec requires GDAL to be built against its internal libtiff.

**Comment by adriancaruana** [comment] 2020-04-23 09:25
Do you know if the `pip` binary is built against internal `libtiff`? Or any other easily available binaries which are?

**Comment by ocefpaf** [comment] 2020-04-23 22:23
Kind of a related question since we got your attention @rouault :smile: 

Do you recommend to use the internal `libtiff`? I always had the impression that it was not recommended and we should use it as a last resort.

**Comment by rouault** [comment] 2020-04-23 22:32
>  I always had the impression that it was not recommended and we should use it as a last resort.

On Unix, then you need to build with --with-rename-internal-libtiff-symbols to avoid any potential clash with other external libtiff. Not sure about the implication on Windows

**Comment by gillins** [comment] 2020-04-23 23:51
> Not sure about the implication on Windows

Hi @rouault I can't see a way to do this on Windows - am I missing something? I think we would need a way of doing this before using internal `libtiff`...

Are you planning to upstream GDAL's internal `libtiff` changes?

**Comment by rouault** [comment] 2020-04-24 00:02
> I can't see a way to do this on Windows - am I missing something?

No, but I believe Windows symbol resolving is a bit less aggressive than Linux, so it might potentially not be needed to do any symbol renaming. But I won't bet one cent on this :-)

> Are you planning to upstream GDAL's internal `libtiff` changes?

Absolutely not :-): there are no GDAL specific libtiff change. GDAL's internal libtiff is identical to upstream libtiff (for the file it borrows), and it is taken in sync with upstream changes regularly. It is mostly a historical convenience to build GDAL (on Windows in particular)
The case of the LERC codec is particular. A libtiff codec needs access to the tiffiop.h private header. So there's no other choice if you want the LERC codec than enabling GDAL's internal libtiff copy. In theory, nothing would prevent to move the LERC codec to upstream libtiff (nothing GDAL specific in it), but this is probably a too niche one to bother the libtiff community with it, since the TIFF LERC codec relies on libLERC to do the actual compression job, and I'm not sure if libLERC has a proper build system.

**Comment by Jean-Roc** [comment] 2020-05-03 20:06
Thanks @rouault for this explanation, we just had this issue on conda on windows/linux and were investigating the cause. We will fallback to gisinternal's builds or osgeo4w

**Comment by gillins** [comment] 2020-05-05 02:02
BTW seems symbol resolution on Windows is indeed different - http://blog.omega-prime.co.uk/2011/07/04/everything-you-never-wanted-to-know-about-dlls/ - seems the DLL name is recorded next to each symbol so the symbol renaming isn't needed anyway. Does anyone have experience of this?

@conda-forge/gdal should we be swapping to internal builds for TIFF and JPEG? Internal TIFF would address this issue, and internal JPEG would give us 12 bit compression (see https://github.com/conda-forge/gdal-feedstock/pull/255)...

**Comment by kmuehlbauer** [comment] 2020-05-05 04:14
@gillins Good question. If we could somehow assess the Pro's and Con's of switching to the internal builds, then we would have a base for discussion and decision.

We could approach gdal-dev list and ask for guidance. It seems that internal libtiff is same as external but the build will be more convenient, IIUC @rouault's comment above.

**Comment by ocefpaf** [comment] 2020-05-06 20:26
> @conda-forge/gdal should we be swapping to internal builds for TIFF and JPEG? Internal TIFF would address this issue, and internal JPEG would give us 12 bit compression (see #255)...

I'm OK giving it a go. If we find any major hiccups we can remove the packages and revert to the current way of building `gdal`.

**Comment by rouault** [comment] 2020-05-06 20:43
Using internal JPEG will loose libjpeg-turbo SSE2 optimizations. I'd tend to think that 12 bit JPEG compression, as standalone JPEG or as JPEG-in-TIFF, is only a marginal use case, that isn't worth loose libjpeg-turbo speed benefits. In an ideal world, we'd be able to use libjpeg-turbo for 8-bit JPEG and the internal build of libjpeg-6b for 12 bit JPEG, but that's not currently possible.

**Comment by gillins** [comment] 2020-05-06 22:50
Thanks @rouault we aren't using libjpeg-turbo - still the original jpeg from ijg.org (there was some talk of changing but not sure where this got to). I've just noticed that there doesn't seem to be a way of renaming internal jpeg symbols anyway - so we'd probably have to stick with external to avoid clashes.

I'll put together a PR for internal libtiff once we have gdal building again...

**Comment by rouault** [comment] 2020-05-06 22:55
>  we aren't using libjpeg-turbo

libjpeg-turbo is a must ! Debian/Ubuntu use it since ages now

**Comment by klassenjs** [comment] 2021-02-11 19:43
As much as I dislike me too comments... 

I am also interested in the GDAL build on conda having LERC support.  Right now I'm building my own conda package locally (so far only on linux) to enable LERC.

The relevant configure options I used in build.sh are:

```
--with-geotiff=internal \
--with-rename-internal-libgeotiff-symbols=yes \
--with-lerc \
--with-libtiff=internal \
--with-rename-internal-libtiff-symbols=yes
```

**Comment by gillins** [comment] 2021-02-12 05:33
Hi @klassenjs feel like submitting a PR? I never got around to doing this :smile:

**Comment by rouault** [comment] 2021-02-28 10:36
There's a pull request to libtiff to add the LERC plugin to it https://gitlab.com/libtiff/libtiff/-/merge_requests/228 . Will require libtiff to be linked against liblerc

**Comment by gillins** [comment] 2021-02-28 23:27
Thanks for letting us know @rouault I think my preferred option would be to wait for this to be merged into `libtiff` (we already have builds of `liblerc`) rather than use the internal build. Any thoughts @conda-forge/gdal ?

**Comment by gillins** [comment] 2021-03-10 23:46
Thanks @rouault we will keep an eye out for a new `libtiff` release and add Lerc support. Yay!

One thing: I assume we wouldn't have to make a change to the way we build `gdal` to get Lerc support (once we have an updated `libtiff`)?

**Comment by rouault** [comment] 2021-03-10 23:58
> One thing: I assume we wouldn't have to make a change to the way we build `gdal` to get Lerc support (once we have an updated `libtiff`)?

correct. But that will require GDAL 3.3

**Comment by rouault** [comment] 2021-04-20 12:08
libtiff 4.3.0 with LERC support has now been released : https://lists.osgeo.org/pipermail/gdal-announce/2021-April/000088.html . GDAL 3.3 should be released within the next 2 weeks

**Comment by gillins** [comment] 2021-06-13 00:51
Can someone confirm this is now fixed on master (gdal 3.3)? libtiff 4.30 should now be picked up in new environments.

**Comment by ocefpaf** [comment] 2021-06-14 16:36
I can confirm that on Linux `conda create --name TEST gdal=3.3` pulls `libtiff 4.3.0`. Thanks for all that worked on this!!

**Comment by klassenjs** [comment] 2021-06-14 22:42
Thanks everyone!

**Comment by avalentino** [comment] 2021-06-26 06:55
I suppose that this issue can be closed now. Correct?

**Comment by gillins** [comment] 2021-06-26 06:59
I think so, but not sure if anyone has actually tested a LERC compressed file?

**Comment by avalentino** [comment] 2021-06-26 07:15
I made a quick test by generateing a LERC compressed COG and then inspecting it with `gdalinfo`.
All works fine of course.
I suppose that this can be considered enough considering the GDAL and libtiff have their own test suite.

**Comment by kmuehlbauer** [comment] 2021-06-26 07:20
Thanks again to everyone making this possible.

**Closed** 2021-06-26 07:20 UTC
