### ISSUE TITLE
install in fresh environment gives ImportError. (Symbol not found: _crc32)

### ISSUE THREAD

**Issue by kwdseymour** [conda-forge/gdal-feedstock#382] opened 2020-04-28 13:33 UTC
Issue:
I have created a fresh conda environment and installed python and gdal with strict conda-forge channel. When I try to import gdal, I receive the following error:

`ImportError: dlopen(/Users/username/anaconda3/envs/GIS/lib/python3.8/site-packages/osgeo/_gdal.cpython-38-darwin.so, 2): Symbol not found: _crc32
  Referenced from: /Users/username/anaconda3/envs/GIS/lib/libgdal.26.dylib
  Expected in: /Users/username/anaconda3/envs/GIS/lib/libcfitsio.8.dylib
 in /Users/username/anaconda3/envs/GIS/lib/libgdal.26.dylib`

Creating other environments and installing other builds generates the same error.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
Name                    Version                   Build  Channel
boost-cpp                 1.72.0               hdf9ef73_0    conda-forge
bzip2                     1.0.8                h0b31af3_2    conda-forge
ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
cairo                     1.16.0            hec6a9b0_1003    conda-forge
certifi                   2020.4.5.1       py38h32f6830_0    conda-forge
cfitsio                   3.470                h35c4aa5_3    conda-forge
curl                      7.69.1               h2d98d24_0    conda-forge
expat                     2.2.9                h4a8c4bd_2    conda-forge
fontconfig                2.13.1            h6b1039f_1001    conda-forge
freetype                  2.10.1               h8da9a1a_0    conda-forge
freexl                    1.0.5             h1de35cc_1002    conda-forge
gdal                      3.0.4            py38h9f7df5a_8    conda-forge
geos                      3.8.1                h4a8c4bd_0    conda-forge
geotiff                   1.5.1               hd8796ba_10    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
giflib                    5.2.1                h0b31af3_2    conda-forge
glib                      2.64.2               h577aef8_0    conda-forge
hdf4                      4.2.13            h84186c3_1003    conda-forge
hdf5                      1.10.6          nompi_h3e39495_100    conda-forge
icu                       64.2                 h6de7cb9_1    conda-forge
jpeg                      9c                h1de35cc_1001    conda-forge
json-c                    0.13.1            h1de35cc_1001    conda-forge
kealib                    1.4.13               h40102fb_1    conda-forge
krb5                      1.17.1               h1752a42_0    conda-forge
libblas                   3.8.0               16_openblas    conda-forge
libcblas                  3.8.0               16_openblas    conda-forge
libcurl                   7.69.1               hc0b9707_0    conda-forge
libcxx                    10.0.0               h1af66ff_2    conda-forge
libdap4                   3.20.6               h8c15375_0    conda-forge
libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
libffi                    3.2.1             h4a8c4bd_1007    conda-forge
libgdal                   3.0.4                h1772500_8    conda-forge
libgfortran               4.0.0                         2    conda-forge
libiconv                  1.15              h0b31af3_1006    conda-forge
libkml                    1.3.0             h169b8f9_1011    conda-forge
liblapack                 3.8.0               16_openblas    conda-forge
libnetcdf                 4.7.4           nompi_ha11d67f_102    conda-forge
libopenblas               0.3.9                h3d69b6c_0    conda-forge
libpng                    1.6.37               hbbe82c9_1    conda-forge
libpq                     12.2                 h489d428_1    conda-forge
libspatialite             4.3.0a            h658e6c1_1038    conda-forge
libssh2                   1.8.2                hcdc9a53_2    conda-forge
libtiff                   4.1.0                h2ae36a8_6    conda-forge
libwebp-base              1.1.0                h0b31af3_3    conda-forge
libxml2                   2.9.10               h53d96d6_0    conda-forge
llvm-openmp               10.0.0               h28b9765_0    conda-forge
lz4-c                     1.9.2                h4a8c4bd_0    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
numpy                     1.18.1           py38h1f821a2_1    conda-forge
openjpeg                  2.3.1                h254dc36_3    conda-forge
openssl                   1.1.1g               h0b31af3_0    conda-forge
pcre                      8.44                 h4a8c4bd_0    conda-forge
pip                       20.0.2                     py_2    conda-forge
pixman                    0.38.0            h01d97ff_1003    conda-forge
poppler                   0.87.0               h3232a60_1    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                12.2                 h62ab893_1    conda-forge
proj                      7.0.0                hbce2d5c_3    conda-forge
python                    3.8.2           hd5f0129_7_cpython    conda-forge
python_abi                3.8                      1_cp38    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
setuptools                46.1.3           py38h32f6830_0    conda-forge
sqlite                    3.30.1               h93121df_0    conda-forge
tbb                       2018.0.5             h2d50403_0    conda-forge
tiledb                    1.7.7                h84aa2a7_1    conda-forge
tk                        8.6.10               hbbe82c9_0    conda-forge
tzcode                    2020a                h0b31af3_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xerces-c                  3.2.2             h8f8adb3_1004    conda-forge
xz                        5.2.5                h0b31af3_0    conda-forge
zlib                      1.2.11            h0b31af3_1006    conda-forge
zstd                      1.4.4                h4b3e974_3    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
active environment : GIS
    active env location : /Users/username/anaconda3/envs/GIS
            shell level : 2
       user config file : /Users/username/.condarc
 populated config files : /Users/username/.condarc
          conda version : 4.8.3
    conda-build version : 3.18.11
         python version : 3.6.8.final.0
       virtual packages : __osx=10.15.4
       base environment : /Users/username/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/username/anaconda3/pkgs
                          /Users/username/.conda/pkgs
       envs directories : /Users/username/anaconda3/envs
                          /Users/username/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.6.8 Darwin/19.4.0 OSX/10.15.4
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
</details>

**Comment by cbworden** [comment] 2020-04-28 20:52
I have the same issue. It's seems to be a MacOS (10.13, 10.14, 10.15) problem. Linux appears to build correctly.

**Comment by rbeyer** [comment] 2020-04-28 21:22
I'm on macOS 10.14 and can confirm this error.  Work around:
- create a clean conda python environment with python=3.6, python=3.7, or the default (which provides python=3.8)
- `conda install gdal=3.0.1` 
- fire up python
- `from osgeo import gdal` has no errors!

However, gdal=3.0.2, 3.0.3, and 3.0.4 seem to be yielding this problem.

**Comment by gillins** [comment] 2020-04-28 22:34
Related to this: https://github.com/conda-forge/cfitsio-feedstock/pull/22 ?

**Comment by isuruf** [comment] 2020-04-29 16:46
Duplicate of https://github.com/conda-forge/cfitsio-feedstock/issues/23

**Closed by isuruf** 2020-04-29 16:46 UTC
