### ISSUE TITLE
libgdal v3.0.1 is linked against libtiledb.so.1.6.0

### ISSUE THREAD

**Issue by microe** [conda-forge/gdal-feedstock#328] opened 2019-08-19 17:16 UTC
Issue: libgdal v3.0.1 is linked to libtiledb.so.1.6.0. Should (hopefully) be libtiledb.so.1

The v3.0.1 package of libdgal is linked to libtiledb.so.1.6.0. This means that any users of libgdal who link with this conda package has to install the 1.6.0 version of tiledb, even though the newer v1.6.2 is available.

FWIW, libgdal should probably be linking to libtiledb.so.1 as long as tiledb is following shared object versioning conventions. But if that is not possible, the meta.yaml should point out this version dependency (like libpoppler).

**Comment by djhoese** [comment] 2019-08-19 18:26
Duplicate of https://github.com/conda-forge/gdal-feedstock/issues/327

**Closed** 2019-08-19 22:08 UTC
