### ISSUE TITLE
Improper linking? ModuleNotFoundError: No module named '_gdal'

### ISSUE THREAD

**Issue by four43** [conda-forge/gdal-feedstock#654] opened 2022-10-21 16:48 UTC
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

When installing in a fresh environment, python is unable to load `_gdal` script.

System: Debian 11, `Linux [hostname] 5.10.0-18-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux`

Reproduction steps, ensuring conda-forge is used. That seems to be a common misstep.
```
$ conda create --name gdal-test --yes
$ conda activate gdal-test
$ conda install --yes --override-channels -c conda-forge gdal
```
Then in that same shell session:
```
$ python
Python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:36:39) [GCC 10.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from osgeo import gdal
Traceback (most recent call last):
  File "/opt/conda/envs/gdal-test/lib/python3.10/site-packages/osgeo/__init__.py", line 30, in swig_import_helper
    return importlib.import_module(mname)
  File "/opt/conda/envs/gdal-test/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 674, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1176, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: libtiledb.so.2.11: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/gdal-test/lib/python3.10/site-packages/osgeo/__init__.py", line 46, in <module>
    _gdal = swig_import_helper()
  File "/opt/conda/envs/gdal-test/lib/python3.10/site-packages/osgeo/__init__.py", line 43, in swig_import_helper
    return importlib.import_module('_gdal')
  File "/opt/conda/envs/gdal-test/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_gdal'
```
Dang libtiledb! Contents of osgeo dir:
```
$ ls -lah /opt/conda/envs/gdal-test/lib/python3.10/site-packages/osgeo
total 2.8M
drwxr-xr-x  3 smiller admin 4.0K Oct 21 11:42 .
drwxr-xr-x 15 smiller admin 4.0K Oct 21 11:42 ..
drwxr-xr-x  2 smiller admin 4.0K Oct 21 11:42 __pycache__
-rwxrwxr-x  2 smiller admin 122K Oct 19 16:28 _gdal_array.cpython-310-x86_64-linux-gnu.so
-rw-rw-r--  2 smiller admin  26K Sep  2 07:20 gdal_array.py
-rwxrwxr-x  2 smiller admin  45K Oct 19 16:28 _gdalconst.cpython-310-x86_64-linux-gnu.so
-rw-rw-r--  2 smiller admin  11K Sep  2 07:20 gdalconst.py
-rwxrwxr-x  2 smiller admin 883K Oct 19 16:28 _gdal.cpython-310-x86_64-linux-gnu.so
-rw-rw-r--  2 smiller admin  214 Sep  2 07:20 gdalnumeric.py
-rw-rw-r--  2 smiller admin 190K Sep  2 07:20 gdal.py
-rwxrwxr-x  2 smiller admin 104K Oct 19 16:28 _gnm.cpython-310-x86_64-linux-gnu.so
-rw-rw-r--  2 smiller admin 9.2K Sep  2 07:20 gnm.py
-rw-rw-r--  2 smiller admin 5.3K Sep  2 07:20 __init__.py
-rwxrwxr-x  2 smiller admin 749K Oct 19 16:28 _ogr.cpython-310-x86_64-linux-gnu.so
-rw-rw-r--  2 smiller admin 257K Sep  2 07:20 ogr.py
-rwxrwxr-x  2 smiller admin 353K Oct 19 16:28 _osr.cpython-310-x86_64-linux-gnu.so
-rw-rw-r--  2 smiller admin  52K Sep  2 07:20 osr.py
-rw-rw-r--  2 smiller admin  190 Sep  2 07:20 utils.py
```

Is this a linking issue? I feel like I'm missing something obvious...

Thanks all

### Installed packages

```shell
conda list
# packages in environment at /opt/conda/envs/gdal-test:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
blosc                     1.21.1               h83bc5f7_3    conda-forge
boost-cpp                 1.78.0               h75c5d50_1    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.9.24            ha878542_0    conda-forge
cairo                     1.16.0            ha61ee94_1014    conda-forge
cfitsio                   4.1.0                hd9d235c_0    conda-forge
curl                      7.85.0               h2283fc2_0    conda-forge
expat                     2.4.9                h27087fc_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.0               hc2a2eb6_1    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.12.1               hca18f0e_0    conda-forge
freexl                    1.0.6                h166bdaf_1    conda-forge
gdal                      3.5.2           py310he53f9b6_4    conda-forge
geos                      3.11.0               h27087fc_0    conda-forge
geotiff                   1.7.1                h4fc65e6_3    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
hdf4                      4.2.15               h9772cbc_4    conda-forge
hdf5                      1.12.2          nompi_h4df4325_100    conda-forge
icu                       70.1                 h27087fc_0    conda-forge
jpeg                      9e                   h166bdaf_2    conda-forge
json-c                    0.16                 hc379101_0    conda-forge
kealib                    1.4.15               ha7026e8_1    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.19.3               h08a2579_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.39                 hc81fddc_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libcurl                   7.85.0               h2283fc2_0    conda-forge
libdap4                   3.20.6               hd7c4107_2    conda-forge
libdeflate                1.14                 h166bdaf_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_18    conda-forge
libgdal                   3.5.2                h6e88209_4    conda-forge
libgfortran-ng            12.2.0              h69a702a_18    conda-forge
libgfortran5              12.2.0              h337968e_18    conda-forge
libglib                   2.74.0               h7a41b64_0    conda-forge
libgomp                   12.2.0              h65d4601_18    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libkml                    1.3.0             h37653c0_1015    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libnetcdf                 4.8.1           nompi_h21705cb_104    conda-forge
libnghttp2                1.47.0               hff17c54_1    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libpng                    1.6.38               h753d276_0    conda-forge
libpq                     14.5                 he2d8382_0    conda-forge
librttopo                 1.1.0               hf730bdb_11    conda-forge
libspatialite             5.0.1               h38b5f51_18    conda-forge
libsqlite                 3.39.4               h753d276_0    conda-forge
libssh2                   1.10.0               hf14f497_3    conda-forge
libstdcxx-ng              12.2.0              h46fd767_18    conda-forge
libtiff                   4.4.0                h55922b4_4    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp-base              1.2.4                h166bdaf_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxml2                   2.9.14               h22db469_4    conda-forge
libzip                    1.9.2                hc929e4a_1    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
nspr                      4.32                 h9c3ff4c_1    conda-forge
nss                       3.78                 h2350873_0    conda-forge
numpy                     1.23.4          py310h53a5b5f_0    conda-forge
openjpeg                  2.5.0                h7d73246_1    conda-forge
openssl                   3.0.5                h166bdaf_2    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pcre2                     10.37                hc3806b6_1    conda-forge
pip                       22.3               pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
poppler                   22.10.0              h92391eb_0    conda-forge
poppler-data              0.4.11               hd8ed1ab_0    conda-forge
postgresql                14.5                 ha7cec9f_0    conda-forge
proj                      9.0.1                h93bde94_1    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
python                    3.10.6          ha86cf86_0_cpython    conda-forge
python_abi                3.10                    2_cp310    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
setuptools                65.5.0             pyhd8ed1ab_0    conda-forge
snappy                    1.1.9                hbd366e4_1    conda-forge
sqlite                    3.39.4               h4ff8645_0    conda-forge
tiledb                    2.12.0               h3f4058f_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tzcode                    2022e                h166bdaf_0    conda-forge
tzdata                    2022e                h191b570_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xerces-c                  3.2.4                h55805fa_1    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zlib                      1.2.13               h166bdaf_4    conda-forge
zstd                      1.5.2                h6239696_4    conda-forge
```

### Environment info

```shell
conda info

     active environment : gdal-test
    active env location : /opt/conda/envs/gdal-test
            shell level : 6
       user config file : /home/smiller/.condarc
 populated config files : /home/smiller/.condarc
          conda version : 22.9.0
    conda-build version : not installed
         python version : 3.9.13.final.0
       virtual packages : __cuda=11.4=0
                          __linux=5.10.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/conda  (writable)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /home/smiller/.conda/pkgs
       envs directories : /opt/conda/envs
                          /home/smiller/.conda/envs
               platform : linux-64
             user-agent : conda/22.9.0 requests/2.28.1 CPython/3.9.13 Linux/5.10.0-18-amd64 debian/11 glibc/2.31
                UID:GID : 2001:3000
             netrc file : None
           offline mode : False
```

**Comment by xylar** [comment] 2022-10-21 16:53
This is the same issue as https://github.com/conda-forge/tiledb-feedstock/issues/170, but it make sense to keep track of it here, too.

**Comment by xylar** [comment] 2022-10-21 19:29
https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/340 should fix this and https://github.com/conda-forge/tiledb-feedstock/pull/172 will keep it from happening again.

**Comment by four43** [comment] 2022-10-21 19:31
@xylar Thanks for getting back to me so promptly. I'll keep an eye over there too.

**Comment by xylar** [comment] 2022-10-22 06:55
A temporary fix would be to explicitly install `tiledb=2.11.3`.

**Comment by xylar** [comment] 2022-10-22 18:27
We're getting there.  All the necessary PRs have been merged:
https://github.com/conda-forge/tiledb-feedstock/pull/171
https://github.com/conda-forge/tiledb-feedstock/pull/172
https://github.com/conda-forge/admin-requests/pull/500
https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/340
We just need to wait for CI to do its think.  I just tested and the problem is still there.

**Comment by four43** [comment] 2022-10-22 18:36
Thanks for all those patches! Using your recommended pinned version I get:
```
27 passed
```
from my tests, so I'm all happy over here :D 

Thanks again for all your effort on this.

**Comment by xylar** [comment] 2022-10-22 18:58
Okay I just ran:
```
 mamba create -y -n test gdal
 mamba activate test
 python -c "from osgeo import gdal"
```
Everything looks okay so I'm closing this.

**Closed by xylar** 2022-10-22 18:58 UTC
Labels: bug

**Comment by bgruening** [comment] 2022-10-22 19:00
Thanks a lot @xylar!
