### ISSUE TITLE
`gdal` installed from `conda-forge` as a dependency fails to install properly but no alarm raised (old OS with very early GLIBC, `fiona` main package)

### ISSUE THREAD

**Issue by valeriupredoi** [conda-forge/gdal-feedstock#606] opened 2022-02-22 18:41 UTC
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

## Context

Hey guys, something that might help others if you consider implementing a fix for this issue; not critical, but nice :grin: I first went to the main GDAL GH repo, but as is the case with more and more packages, they don't do the binary packaging so they sent me over here from https://github.com/OSGeo/gdal/issues/5375

Here's the setting: I am on a machine that has a very old OS, hence a very early GLIBC, and I am creating a `conda` environment with `miniconda`, I am installing a package there that needs `gdal` as dependency (e.g. installing `fiona` that will install `gdal` as its dependency), then I am trying to use the package that I just installed in my virtual env, and all hell breaks loose from the get going. Most of the times the errors I'll get will be obscure, and will marginally point to an issue with `gdal` if at all, let alone telling me that `gdal` was not properly installed; if I run me a `gdalinfo --version` or any executable from within `gdal` the issue will become obvious (see below), but sometimes it won't be straightforward that there is a faulty installation of GDAL in the midst of the kerfuffle so a user will not even think of checking if the `gdal` installation went well; conda says nothing and tells you all packages were installed correctly.

## Expected behavior and actual behavior.

A conda/mamba installation of a package that needs GDAL as a dependency, therefore installs it in a Python virtual environment, does not raise any alarm bells if GDAL was not installed correctly due to an old GLIBC (fails silently?), I would expect a warning, if not an exception and termination of the install process if the required `GLIBC_2.xx` is not found.

## Steps to reproduce the problem.

`mamba install -c conda-forge fiona` on a machine with GLIBC<2.14

## Operating system

```
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 6.10 (Santiago)
Release:        6.10
Codename:       Santiago

> ldd --version
ldd (GNU libc) 2.12
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

## GDAL version and provenance

```

> mamba --version
mamba 0.21.2
conda 4.11.0

> python -V
Python 3.10.2

> mamba list gcc && mamba list gxx
# packages in environment at /mnt/lustre02/work/bd0854/b309141/mambaforge/envs/xxx:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
gcc                       9.4.0                h192d537_5    conda-forge
gcc_impl_linux-64         9.4.0               h03d3576_12    conda-forge
gcc_linux-64              9.4.0                h391b98a_5    conda-forge
libgcc-devel_linux-64     9.4.0               hd854feb_12    conda-forge
libgcc-ng                 11.2.0              h1d223b6_12    conda-forge
# packages in environment at /mnt/lustre02/work/bd0854/b309141/mambaforge/envs/xxx:
#
# Name                    Version                   Build  Channel
gxx                       9.4.0                h192d537_5    conda-forge
gxx_impl_linux-64         9.4.0               h03d3576_12    conda-forge
gxx_linux-64              9.4.0                h0316aca_5    conda-forge

> mamba list gdal
# packages in environment at /mnt/lustre02/work/bd0854/b309141/mambaforge/envs/xxx:
#
# Name                    Version                   Build  Channel
gdal                      3.4.1           py310h222ae0d_3    conda-forge
libgdal                   3.4.1                hc3d8651_3    conda-forge
```

## Here's where the show stops

```
> which gdalinfo && gdalinfo --version
/mnt/lustre02/work/bd0854/b309141/mambaforge/envs/xxx/bin/gdalinfo
gdalinfo: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /mnt/lustre02/work/bd0854/b309141/mambaforge/envs/xxx/bin/../lib/libgdal.so.30)
gdalinfo: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /mnt/lustre02/work/bd0854/b309141/mambaforge/envs/xxx/bin/../lib/libgdal.so.30)
```

but before that, trying to use my new shiny `fiona` is akin to a fight with a tiger in a jungle at night, e.g.:

```
$ esmvaltool run examples/recipe_python.yml
ERROR:esmvalcore._main:Program terminated abnormally, see stack trace below for more information:
Traceback (most recent call last):
  File "/work/bd0854/b309192/soft/miniconda3/envs/test/lib/python3.10/site-packages/esmvalcore/_main.py", line 479, in run
    fire.Fire(ESMValTool())
  File "/work/bd0854/b309192/soft/miniconda3/envs/test/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/work/bd0854/b309192/soft/miniconda3/envs/test/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/work/bd0854/b309192/soft/miniconda3/envs/test/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/work/bd0854/b309192/soft/miniconda3/envs/test/lib/python3.10/site-packages/esmvalcore/_main.py", line 376, in run
    from ._recipe import TASKSEP
  File "/work/bd0854/b309192/soft/miniconda3/envs/test/lib/python3.10/site-packages/esmvalcore/_recipe.py", line 15, in <module>
    from . import _recipe_checks as check
  File "/work/bd0854/b309192/soft/miniconda3/envs/test/lib/python3.10/site-packages/esmvalcore/_recipe_checks.py", line 13, in <module>
    from .preprocessor import TIME_PREPROCESSORS, PreprocessingTask
  File "/work/bd0854/b309192/soft/miniconda3/envs/test/lib/python3.10/site-packages/esmvalcore/preprocessor/__init__.py", line 14, in <module>
    from ._area import (
  File "/work/bd0854/b309192/soft/miniconda3/envs/test/lib/python3.10/site-packages/esmvalcore/preprocessor/_area.py", line 9, in <module>
    import fiona
  File "/work/bd0854/b309192/soft/miniconda3/envs/test/lib/python3.10/site-packages/fiona/__init__.py", line 85, in <module>
    with fiona._loading.add_gdal_dll_directories():
AttributeError: partially initialized module 'fiona' has no attribute '_loading' (most likely due to a circular import)
```

trace which barely touches upon the fact that there may be something awry with GDAL.

Cheers muchly! :beer:

**Comment by ocefpaf** [comment] 2022-02-22 18:46
I'm not sure if the move [announced here](https://conda-forge.org/docs/user/announcements.html?#id3) started yet but `glibc 2.12` should still be the expected one for most of our packages. Can you try downgrading the versions and check if that one works with your old setup?

**Comment by valeriupredoi** [comment] 2022-02-22 19:08
@ocefpaf good to see you here too, mate! Yes, downgrading to `gdal=3.4.0` and `fiona=1.8.20` works well, but that's only a local change on the particular cluster with that old GLIBC that @schlunma and @remi-kazeroni will do, no way we can roll our package out with those pins in there. It doesn't matter too much for us anyway since that particular cluster will get the OS updated soon, I was just raising this more like a heads up maybe others get in the same pickle :beer:

**Comment by gillins** [comment] 2022-02-22 22:27
I'm wondering if this is related the change we recently made to the version of COS used to build `gdal` (https://github.com/conda-forge/gdal-feedstock/pull/604)?

I have heard people being caught out by have an old `glibc` before... Would be good if conda reported an error about this during installation.

**Comment by ocefpaf** [comment] 2022-02-23 10:43
Oh! I missed that PR. That is probably the cause. We don't have to revert though b/c all of conda-forge is slowly moving to a newer glibc this year. We just need to do a better job at announcing it.

**Comment by valeriupredoi** [comment] 2022-02-23 16:16
cool, cheers, guys! Yeah, conda is moving to glibc=2.17(min) from Felipe's https://github.com/conda-forge/gdal-feedstock/issues/606#issuecomment-1048104659 - which is a bit of a monster since I know at least two HPC's that I use that are still on 2.14 :man_facepalming: At any rate, you guys can close this from my perspective, since now you are aware of it, and I know what to keep my eyes open for too next time I see an odd GDAL-related issue, thanks for your input :beer:

**Comment by ocefpaf** [comment] 2022-02-23 20:04
Good luck. As someone who also maintain some HPC envs with old glibc I know what your are going through.

**Comment by zklaus** [comment] 2022-02-24 09:47
@ocefpaf, that kind of all makes sense, but shouldn't the package then in some way depend on the `__glibc>=2.17`?

**Comment by zklaus** [comment] 2022-02-24 09:54
Looking further into this, I'd like to ask this issue be reopened. I think since build requirements contain sysroot 2.17, host requirements should get `__glibc >=2.17`. Older builds would need a repo patch or be marked broken.

**Comment by ocefpaf** [comment] 2022-02-24 10:57
> I think since build requirements contain sysroot 2.17, run requirements should get `__glibc >=2.17`

Indeed.

> Older builds would need a repo patch or be marked broken.

Better to a repodata patch.

**Comment by zklaus** [comment] 2022-02-24 10:58
I am chatting about that right now on gitter. The real solution is a bit different. Let me elaborate in a second before we take action.

**Comment by zklaus** [comment] 2022-02-24 11:04
Essentially, the multi-output nature of the package throws things off. The `libgdal` output should depend on the `sysroot`, but overall we should probably get rid of the entire requirements section in the main package and integrate it into the corresponding sections in the outputs, similar to how it's done in https://github.com/conda-forge/mamba-feedstock/blob/master/recipe/meta.yaml.

Does that sound ok?

**Comment by ocefpaf** [comment] 2022-02-24 13:44
> Does that sound ok?

Yes. I don't have the time to address this now and it seems that you are on top of things. Do you mind sending a PR to do that?

**Comment by zklaus** [comment] 2022-02-24 13:46
#607 :smile:

**Comment by xylar** [comment] 2022-02-24 15:30
Thanks for this work @zklaus!  As I think you probably realized in the process of making #607, it would be really nice if we didn't need the redundant requirements at the top of the package because they cause confusion like happened in #604 but conda-smithy seems to need them to maintain the pins correctly.

**Comment by zklaus** [comment] 2022-02-24 15:32
Yeah, I noticed something was going on. I rationalized that for some reason the actual building of everything happens before we reach the outputs stages, which then only select some files from the already pre-built directory, but I am never quite sure with multi-outputs.

**Comment by zklaus** [comment] 2022-02-24 15:49
An update on the afflicted branches: Thankfully, it is only main, i.e. >=3.4.x that uses the newer sysroot and needs a repo patch.

**Comment by valeriupredoi** [comment] 2022-02-24 16:25
this can be closed now :+1:

**Comment by zklaus** [comment] 2022-02-24 16:26
Not yet. We still need the repodata patch.

**Comment by zklaus** [comment] 2022-02-25 13:05
The repodata patch is now available in conda-forge/conda-forge-repodata-patches-feedstock#232. Once that is merged, this issue should be closed automatically.

**Comment by valeriupredoi** [comment] 2022-02-25 13:18
![excelente-burns](https://user-images.githubusercontent.com/28983971/155721715-599c2eb4-8378-4cff-8ea0-ccce69929da6.gif)

**Closed** 2022-02-25 15:44 UTC
