### ISSUE TITLE
ISIS3/USGS driver problem

### ISSUE THREAD

**Issue by michaelaye** [conda-forge/gdal-feedstock#46] opened 2016-04-27 00:16 UTC
This version (or maybe only this compile) suffers from a recently popping up problem with USGS ISIS3 cube files. It was previously seen years ago, when it was suggested that it can happen from an unclean compile, see here for a discussion:
https://lists.osgeo.org/pipermail/gdal-dev/2009-September/022101.html

Symptom: Opening an USGS ISIS cube errors with:
```bash
ERROR 6: SetNoDataValue() not supported for this dataset.
ERROR 6: SetOffset() not supported on this raster band.
ERROR 6: SetScale() not supported on this raster band.
```
while this driver is well supported for many years.

I just tried the recently updated pure conda version of gdal, and that one currently does not have this problem.
Here is a mini cube file to try things out: https://dl.dropboxusercontent.com/u/139035/cropped.cub
When called with this version of gdal it looks like this:
```bash
(gdal_forge)└─❱❱❱ gdalinfo cropped.cub                                                       +5067 18:11 ❰─┘
ERROR 6: SetNoDataValue() not supported for this dataset.
ERROR 6: SetOffset() not supported on this raster band.
ERROR 6: SetScale() not supported on this raster band.
Driver: ISIS3/USGS Astrogeology ISIS cube (Version 3)
Files: cropped.cub
Size is 100, 100
Coordinate System is:
PROJCS["Sinusoidal Mars",
    GEOGCS["GCS_Mars",
        DATUM["D_Mars",
            SPHEROID["Mars",3396190,0]],
        PRIMEM["Reference_Meridian",0],
        UNIT["degree",0.0174532925199433]],
    PROJECTION["Sinusoidal"],
    PARAMETER["longitude_of_center",296.28065864847],
    PARAMETER["false_easting",0],
    PARAMETER["false_northing",0]]
Origin = (-4959.626702915599708,-4803213.120008500292897)
Pixel Size = (0.495566217317710,-0.495566217317710)
Corner Coordinates:
Upper Left  (   -4959.627,-4803213.120) ( 64d15'22.21"W, 81d 1'59.20"S)
Lower Left  (   -4959.627,-4803262.677) ( 64d15'22.39"W, 81d 2' 2.21"S)
Upper Right (   -4910.070,-4803213.120) ( 64d15' 2.90"W, 81d 1'59.20"S)
Lower Right (   -4910.070,-4803262.677) ( 64d15' 3.07"W, 81d 2' 2.21"S)
Center      (   -4934.848,-4803237.898) ( 64d15'12.64"W, 81d 2' 0.70"S)
Band 1 Block=100x100 Type=Float32, ColorInterp=Undefined
```

When called with conda's gdal, it does not show this error:
```bash
(gdal_try)└─❱❱❱ gdalinfo cropped.cub                                                         +5070 18:13 ❰─┘
Driver: ISIS3/USGS Astrogeology ISIS cube (Version 3)
Files: cropped.cub
Size is 100, 100
Coordinate System is:
PROJCS["Sinusoidal Mars",
    GEOGCS["GCS_Mars",
        DATUM["D_Mars",
            SPHEROID["Mars",3396190,0]],
        PRIMEM["Reference_Meridian",0],
        UNIT["degree",0.0174532925199433]],
    PROJECTION["Sinusoidal"],
    PARAMETER["longitude_of_center",296.28065864847],
    PARAMETER["false_easting",0],
    PARAMETER["false_northing",0]]
Origin = (-4959.626702915599708,-4803213.120008500292897)
Pixel Size = (0.495566217317710,-0.495566217317710)
Corner Coordinates:
Upper Left  (   -4959.627,-4803213.120) ( 64d15'22.21"W, 81d 1'59.20"S)
Lower Left  (   -4959.627,-4803262.677) ( 64d15'22.39"W, 81d 2' 2.21"S)
Upper Right (   -4910.070,-4803213.120) ( 64d15' 2.90"W, 81d 1'59.20"S)
Lower Right (   -4910.070,-4803262.677) ( 64d15' 3.07"W, 81d 2' 2.21"S)
Center      (   -4934.848,-4803237.898) ( 64d15'12.64"W, 81d 2' 0.70"S)
Band 1 Block=100x100 Type=Float32, ColorInterp=Undefined
  NoData Value=-3.40282265508890445e+38
```

**Comment by ocefpaf** [comment] 2016-04-27 00:37
Hard one to debug... There is no obvious information in that e-mail thread to help me solve this. The main difference between `gdal` from conda-forge  and the default is the fact that we link against some external libraries, like `giflib`, instead of using `gdal`'s internal version.

I will perform some test tomorrow, but if that is the reason I am puzzled to why `gdal` allows external linking and/or why they haven't send that change upstream.  Anyways... I am not even sure if that is the reason for this issue.

**Comment by michaelaye** [comment] 2016-04-27 00:38
and there's no way the compile of conda-forge's gdal was `dirty` by chance?

**Comment by gillins** [comment] 2016-04-27 00:47
Are you using GDAL 1.x or 2.x? Someone once reported the exact same problem to me, turned out it was a bug introduced in 1.11.3 (or was is 1.11.4?) but fixed in other versions.

**Comment by michaelaye** [comment] 2016-04-27 00:49
All versions are the newest offered per source of package, which is for conda-forge 2.0.2 and for conda's default channel 2.0.0.

**Comment by gillins** [comment] 2016-04-27 01:03
I just checked with a build I did on my own PC and same problem (and that should be clean). Would be interesting to see if the upcoming GDAL 2.1.0 release has the same problem.

**Comment by gillins** [comment] 2016-04-27 01:05
Hang on a moment - the `gdal2` branch does not use giflib (one of the things I mean to sync between the 2). So I don't think this is the problem.

**Comment by ocefpaf** [comment] 2016-04-27 01:06
> and there's no way the compile of conda-forge's gdal was `dirty` by chance?

Not sure you mean by *dirty* as external source for the libs is fair game in `gdal` compilation. Otherwise they sould not look for them at build time and just use the internal ones.

I suspect `giflib` is the culprit. See #47 for a possible fix.

**Comment by ocefpaf** [comment] 2016-04-27 01:09
> Hang on a moment - the `gdal2` branch does not use giflib (one of the things I mean to sync between the 2). So I don't think this is the problem.

Indeed... I will look at this again with fresh eyes tomorrow. (BTW the Windows builds do not suffer from this!)

**Comment by gillins** [comment] 2016-04-27 02:34
Just confirmed that this still happens with GDAL 2.1.0 RC4. I'm a bit baffled.
Weird that it doesn't happen on Windows.

**Comment by gillins** [comment] 2016-04-27 04:02
OK I found that if you remove --without-pam from the configure step it all works fine. This would explain the difference on Windows - that build has PAM (persistent auxiliary metadata) enabled. 
I'm not sure what this means. Does anyone know why PAM was disabled in this build?

**Comment by ceholden** [comment] 2016-04-27 05:56
Aha! I tracked down the issue to PAM being disabled as well and can confirm rebuilding without PAM disabled fixes it. I'm not quite sure what is different about the Planetary Data System (PDS) drivers as they're the only file format included in the [GDAL test data examples](http://download.osgeo.org/gdal/data/) that conda-forge's build supports that complained when `GDAL_PAM_ENABLED=NO`. None of the other supported raster formats in the test examples seemed to mind `GDAL_PAM_ENABLED=YES`.

I guess that the NoDataValues, Offset, and Scale metadata are not included in the ["selected other header metadata"](http://www.gdal.org/frmt_pds.html) that this driver can read. The way the driver's code routed to the error suggests to me that it depends on writing these metadata to a PAM ".aux.xml" file and isn't very accommodating when it can't write PAM files.

I don't know if this is the correct backstory, but if the recipe was ported from the [IOOS channel](https://github.com/ioos/conda-recipes) then the `--without-pam` has been around in the Unix build [since the first commit of the recipe](https://github.com/ioos/conda-recipes/commit/f2a98411ddf1604e82adf0a50a7a8690fb45fe8b). There is [some discussion on the GDAL mailing list from 2007 when they changed PAM to be enabled by default that lacks objections](https://lists.osgeo.org/pipermail/gdal-dev/2007-September/014159.html). I know some of my peers tend to delete these metadata to reduce the number of files on disk (which can make an impact when you dump 1000s of images into one directory). There are a few other motives for disabling PAM I've found, including [a personal preference against the PAM files when batch processing](https://lists.osgeo.org/pipermail/gdal-dev/2009-January/019580.html) and [GDAL reading out of date raster statistics from PAM instead of recomputing](https://lists.osgeo.org/pipermail/gdal-dev/2009-January/019580.html).

The last reason given has tripped me up before, but disabling PAM really clobbers the PDS formats since I'm not sure you can even open the datasets in Python so I would be inclined to enable it barring other objections:

``` bash
> python -c 'from osgeo import gdal; ds = gdal.Open("cropped.cub"); print(ds)'
ERROR 6: SetNoDataValue() not supported for this dataset.
ERROR 6: SetOffset() not supported on this raster band.
ERROR 6: SetScale() not supported on this raster band.
None
> GDAL_PAM_ENABLED=YES python -c 'from osgeo import gdal; ds = gdal.Open("cropped.cub"); print(ds)'
<osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x7f48c8f4e5d0> >
```

**Comment by michaelaye** [comment] 2016-04-27 06:41
Nice work! So, I'm curious then why it currently is working on conda's GDAL? Did somebody deliberate remove the disabling of PAM? Or is that build not inherited from the IOOS recipe?
Btw, your first paragraph must confuse at some point the YES and NO, I think? Do you mean that the PDS driver doesn't like PAM to be enabled?

**Comment by ceholden** [comment] 2016-04-27 07:05
Thanks for the clarifying question -- hopefully my edit is more clear. I just meant that there were no additional problems caused by enabling GDAL to use PAM when running `gdalinfo` against the test data files.

The [official conda recipe for GDAL](https://github.com/conda/conda-recipes/blob/master/gdal/build.sh) differs from conda-forge's because they don't pass `--disable-pam` to the configure step (meaning PAM is enabled by default). The [conda/conda-recipes history for their GDAL Unix build](https://github.com/conda/conda-recipes/commits/master/gdal/build.sh) shows that they've never disabled PAM.

In contrast, the IOOS and conda-forge recipes have always disabled PAM for the Unix builds as far as I can tell. @ocefpaf committed both the IOOS and conda-forge recipes, so he might know more after some much needed rest. @gillins scooped me on the diagnosis :smile:, so I tried to confirm the fix and frame the discussion around re-enabling PAM by default.

**Comment by ceholden** [comment] 2016-04-27 07:22
I missed one of your questions -- you can force the default/official conda build of GDAL to produce the same errors by disabling PAM via the environment variable:

``` bash
> conda list | grep gdal                   
gdal                      2.0.0                    py27_1    defaults
libgdal                   2.0.0                         2    defaults
> gdalinfo cropped.cub | grep ERROR
> GDAL_PAM_ENABLED=NO gdalinfo cropped.cub | grep ERROR
ERROR 6: SetNoDataValue() not supported for this dataset.
ERROR 6: SetOffset() not supported on this raster band.
ERROR 6: SetScale() not supported on this raster band.
```

[This section of the `GDALPamDataset` class (which the ISIS3 format inherits from)](https://github.com/OSGeo/gdal/blob/bca12f7655fac8bc2734c1a8af1cad4f272450ac/gdal/gcore/gdalpamdataset.cpp#L270) describes this behavior. It's basically acting as `dict.get('GDAL_PAM_ENABLED', default_value)` in Python where `default_value` is determined at compile time using [this macro](https://github.com/OSGeo/gdal/blob/bca12f7655fac8bc2734c1a8af1cad4f272450ac/gdal/gcore/gdalpamdataset.cpp#L261). Configuring the build with `--without-pam`, as the conda-forge recipe currently does, sets the default value to `NO` for the GDAL build.

**Comment by ocefpaf** [comment] 2016-04-27 09:40
Thw `--without-pam` was in the original recipe from OSGEO. (See http://anaconda.org/osgeo/gdal/1.11.4/download/osx-64/gdal-1.11.4-py34_1.tar.bz2)

Thanks @gillins and @ceholden for finding the issue! I am updating the #47 to reflect that.

**Comment by gillins** [comment] 2016-04-27 10:21
That recipe was actually from myself and @danclewley. We got annoyed with all the .xml files GDAL would create with PAM. Especially since the formats we used (HFA, KEA etc) already could handle all the information saved in PAM.
I'm guessing the right thing to do is to go back to the default GDAL behaviour (yes to PAM) if that fixes some drivers.
We can always override it in the users environment by setting GDAL_PAM_ENABLED as pointed out above.

**Comment by ocefpaf** [comment] 2016-04-27 14:12
> hat recipe was actually from myself and @danclewley.

And we came full circle :wink: 

Closing this as the issue can be addressed by setting `GDAL_PAM_ENABLED=YES`

(We are still discussing the what should be the default for the package though.)

**Closed by ocefpaf** 2016-04-27 14:12 UTC
