### ISSUE TITLE
Cannot import gdal: libkea.so.1.4 undefined symbol

### ISSUE THREAD

**Issue by trey-stafford** [conda-forge/gdal-feedstock#275] opened 2019-03-22 18:43 UTC
Issue: installing gdal to a new conda environment results in an unusable installation.
```
$ conda create -n test
$ conda activate test
$ conda install gdal
$ python -c "import gdal"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/trst2284/miniconda3/envs/test5/lib/python3.7/site-packages/gdal.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "/home/trst2284/miniconda3/envs/test5/lib/python3.7/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/home/trst2284/miniconda3/envs/test5/lib/python3.7/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/home/trst2284/miniconda3/envs/test5/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/trst2284/miniconda3/envs/test5/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/trst2284/miniconda3/envs/test5/lib/python3.7/site-packages/osgeo/../../.././libkea.so.1.4: undefined symbol: _ZNK2H510H5Location15getObjnameByIdxB5cxx11Ey
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

# Name                    Version                   Build  Channel
boost-cpp                 1.68.0            h11c811c_1000    conda-forge
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
cairo                     1.16.0            ha4e643d_1000    conda-forge
certifi                   2019.3.9                 py37_0    conda-forge
curl                      7.64.0               h646f8bb_2    conda-forge
expat                     2.2.5             hf484d3e_1002    conda-forge
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.10.0               he983fc9_0    conda-forge
freexl                    1.0.5             h14c3975_1002    conda-forge
gdal                      2.4.0           py37hf242f0b_1005    conda-forge
geos                      3.7.1             hf484d3e_1000    conda-forge
geotiff                   1.4.3             h1105359_1000    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
giflib                    5.1.7                h516909a_1    conda-forge
glib                      2.58.3            hf63aee3_1001    conda-forge
hdf4                      4.2.13            h9a582f1_1002    conda-forge
hdf5                      1.10.4          nompi_h5598ddc_1105    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
json-c                    0.13.1            h14c3975_1001    conda-forge
kealib                    1.4.10            h1978553_1003    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libblas                   3.8.0                4_openblas    conda-forge
libcblas                  3.8.0                4_openblas    conda-forge
libcurl                   7.64.0               h541490c_2    conda-forge
libdap4                   3.19.1            hd48c02d_1000    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 8.2.0                hdf63c60_1
libgdal                   2.4.0             hdb8f723_1005    conda-forge
libgfortran               3.0.0                         1    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
libkml                    1.3.0             h328b03d_1009    conda-forge
liblapack                 3.8.0                4_openblas    conda-forge
libnetcdf                 4.6.2             hbdf4f91_1001    conda-forge
libpng                    1.6.36            h84994c4_1000    conda-forge
libpq                     11.2                 h4770945_0    conda-forge
libspatialite             4.3.0a            hb5ec416_1026    conda-forge
libssh2                   1.8.1                h22169c7_0    conda-forge
libstdcxx-ng              8.2.0                hdf63c60_1
libtiff                   4.0.10            h648cc4a_1001    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.8             h143f9aa_1005    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.16.2           py37h8b7e671_1    conda-forge
openblas                  0.3.5                ha44fe06_0    conda-forge
openjpeg                  2.3.0             hf38bd82_1003    conda-forge
openssl                   1.1.1b               h14c3975_1    conda-forge
pcre                      8.41              hf484d3e_1003    conda-forge
pip                       19.0.3                   py37_0    conda-forge
pixman                    0.34.0            h14c3975_1003    conda-forge
poppler                   0.67.0               h2ad7f00_6    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                11.2                 h61314c7_0    conda-forge
proj4                     5.2.0             h14c3975_1001    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
python                    3.7.2                h381d211_0    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
setuptools                40.8.0                   py37_0    conda-forge
sqlite                    3.26.0            h67949de_1001    conda-forge
tk                        8.6.9             h84994c4_1000    conda-forge
tzcode                    2018g             h14c3975_1001    conda-forge
wheel                     0.33.1                   py37_0    conda-forge
xerces-c                  3.2.2             hac72e42_1001    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.9             h516909a_1004    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.7             h14c3975_1000    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
z
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : test5
    active env location : /home/trst2284/miniconda3/envs/test5
            shell level : 1
       user config file : /home/trst2284/.condarc
 populated config files : /home/trst2284/.condarc
          conda version : 4.6.8
    conda-build version : 3.17.8
         python version : 3.7.2.final.0
       base environment : /home/trst2284/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/nsidc/linux-64
                          https://conda.anaconda.org/nsidc/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/nsidc/label/dev/linux-64
                          https://conda.anaconda.org/nsidc/label/dev/noarch
                          https://conda.anaconda.org/conda-forge/channel/dev/linux-64
                          https://conda.anaconda.org/conda-forge/channel/dev/noarch
          package cache : /home/trst2284/miniconda3/pkgs
                          /home/trst2284/.conda/pkgs
       envs directories : /home/trst2284/miniconda3/envs
                          /home/trst2284/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.8 requests/2.21.0 CPython/3.7.2 Linux/4.15.0-46-generic ubuntu/16.04.6 glibc/2.23
                UID:GID : 1000:1000
             netrc file : /home/trst2284/.netrc
           offline mode : False

```
</details>

**Comment by trey-stafford** [comment] 2019-03-22 18:58
This appears to have something to do with libgfortran. A previously created conda environment with gdal installed has `libgfortran-ng`, but freshly created environments do not. Installing `libgfortran-ng` fixes the issue:

```
$ conda install gdal "libgfortran-ng=7.2.0=hdf63c60_3"
$ python -c "import gdal"
$ echo $?
0
```

**Comment by gillins** [comment] 2019-03-23 02:49
@ocefpaf is this related to https://github.com/conda-forge/kealib-feedstock/pull/28? Seems like `kealib` is running against a different build of `hdf5` to what it was built against.

**Comment by gillins** [comment] 2019-03-24 03:55
Seems newest `hdf5` is **not** built in C++11 mode, but `kealib` is (which is the default for conda-forge AFAIK). Hence linking error as symbols are different. Investigating...

**Comment by gillins** [comment] 2019-03-24 06:11
Build 1106 of `hdf5` is fine. Build 1105 seems to have the problem. But I can't work out why new environments want to use build 1105 as they appear to have the same pinning. Maybe 1105 needs to be moved to `broken`?

**Comment by kmuehlbauer** [comment] 2019-03-24 06:59
@gillins @ocefpaf This might be related to the fact, that the ng compilers from cf have been moved to broken label recently. I managed to work around this by using the new strict channel behaviour.

**Comment by ocefpaf** [comment] 2019-03-25 10:36
Sorry. I was out during the weekend and dropped the ball on this one. I rebuild `hdf5`, as @gillies already saw, but did not remove the bad build. Doing that that so we can fix `gdal`.

@kmuehlbauer we removed the compilers b/c we should rely on defaults for them now. Specially with `strict`. That way we don't need to keep copying the compilers over to `conda-forge` every time we need an upgrade.

**Comment by ocefpaf** [comment] 2019-03-25 13:30
Should be fixed now. Please re-open if you are still experiencing,

**Closed by ocefpaf** 2019-03-25 13:30 UTC

**Comment by baloe** [comment] 2019-05-13 14:18
> Should be fixed now. Please re-open if you are still experiencing,

I'm experiencing the error. I ran `conda install gdal` which appeared to be successful, but `from osgeo import ogr` fails with the following message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/s4080143/.conda/envs/pers/lib/python3.6/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/home/s4080143/.conda/envs/pers/lib/python3.6/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/home/s4080143/.conda/envs/pers/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/s4080143/.conda/envs/pers/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libkea.so.1.4.7: cannot open shared object file: No such file or directory
```

What is the solution? Do I have to ask our server admins to update anaconda?

**Comment by ocefpaf** [comment] 2019-05-13 14:52
@baloe please do not comment on a close issue. There is not enough information to help you and sometimes the symptoms are similar but the problem is completely different.
