### ISSUE TITLE
PDAL depending on GDAL 2.3+

### ISSUE THREAD

**Issue by hobu** [conda-forge/gdal-feedstock#236] opened 2018-11-11 16:02 UTC
Sorry if this is not the correct place for this issue.

I'm having a lot of trouble getting the PDAL recipe to pin to conda-forge libgdal 2.3.x. It only ever picks up GDAL 1.11.2-1 from base. When I issue smithy rerender, no dependency items for libgdal are emitted to the .ci_support output despite libgdal being listed in the PDAL meta.yml https://github.com/conda-forge/pdal-feedstock/blob/master/recipe/meta.yaml#L30 

[Latest smithy output here.](https://github.com/conda-forge/pdal-feedstock/pull/42/commits/bfc0f6a0da385b669a4b13a6052ff269c2566dc2)

Is GDAL special in some way? I am a conda packaging newbie and maybe I'm confusing something. Do I need to namespace prefix that PDAL should depend on conda-forge/gdal and not base/gdal somehow? 

Tagging @chambbj on this too, as he's been doing most of the PDAL/Conda bootstrapping...

**Comment by gillins** [comment] 2018-11-11 21:31
Seems ok to me (https://travis-ci.org/conda-forge/pdal-feedstock/jobs/453602215#L487). Where are you seeing it get 1.11.2?

**Comment by chambbj** [comment] 2018-11-11 21:45
I believe the problem is that while it builds as expected, users pulling
into a fresh conda environment are getting the unexpected gdal version.

**Comment by kmuehlbauer** [comment] 2018-11-12 06:09
@chambbj How did they create the fresh environment?

**Comment by kmuehlbauer** [comment] 2018-11-12 07:17
For which python version? 

In a pure `conda-forge` setup (no `defaults` in channel list) I get with:

```bash
conda create -n PDAL pdal
```

```
blas:             1.1-openblas                        conda-forge
    boost-cpp:        1.67.0-h3a22d5f_0                   conda-forge
    bzip2:            1.0.6-h470a237_2                    conda-forge
    ca-certificates:  2018.10.15-ha4d7672_0               conda-forge
    cairo:            1.14.12-he56eebe_3                  conda-forge
    curl:             7.62.0-h74213dd_0                   conda-forge
    expat:            2.2.5-hfc679d8_2                    conda-forge
    flann:            1.9.1-h57d4613_3                    conda-forge
    fontconfig:       2.13.0-h0c61d53_4                   conda-forge
    freetype:         2.8.1-hfa320df_1                    conda-forge
    freexl:           1.0.5-h470a237_2                    conda-forge
    geos:             3.6.2-hfc679d8_3                    conda-forge
    geotiff:          1.4.2-h700e5ad_5                    conda-forge
    gettext:          0.19.8.1-h5e8e0c9_1                 conda-forge
    giflib:           5.1.4-h470a237_1                    conda-forge
    glib:             2.55.0-h464dc38_2                   conda-forge
    hdf4:             4.2.13-h951d187_2                   conda-forge
    hdf5:             1.10.2-hc401514_2                   conda-forge
    hexer:            1.4.0-1                             conda-forge
    icu:              58.2-hfc679d8_0                     conda-forge
    jpeg:             9c-h470a237_1                       conda-forge
    json-c:           0.12.1-h470a237_1                   conda-forge
    jsoncpp:          1.8.1-h2d50403_1                    conda-forge
    kealib:           1.4.9-h0bee7d0_2                    conda-forge
    krb5:             1.16.2-hbb41f41_0                   conda-forge
    laszip:           3.2.2-hfc679d8_2                    conda-forge
    laz-perf:         1.2.0-hfc679d8_2                    conda-forge
    libcurl:          7.62.0-hbdb9355_0                   conda-forge
    libedit:          3.1.20170329-haf1bffa_1             conda-forge
    libffi:           3.2.1-hfc679d8_5                    conda-forge
    libgcc-ng:        7.2.0-hdf63c60_3                    conda-forge
    libgdal:          2.2.4-h25f9fa3_7                    conda-forge
    libgfortran:      3.0.0-1                             conda-forge
    libiconv:         1.15-h470a237_3                     conda-forge
    libkml:           1.3.0-hccc92b1_8                    conda-forge
    libnetcdf:        4.6.1-h628ed10_200                  conda-forge
    libpng:           1.6.34-ha92aebf_2                   conda-forge
    libpq:            10.5-he29860b_0                     conda-forge
    libspatialite:    4.3.0a-hdfcc80b_23                  conda-forge
    libssh2:          1.8.0-h5b517e9_2                    conda-forge
    libstdcxx-ng:     7.2.0-hdf63c60_3                    conda-forge
    libtiff:          4.0.9-he6b73bb_2                    conda-forge
    libuuid:          1.0.3-1                             conda-forge
    libxcb:           1.13-h470a237_2                     conda-forge
    libxml2:          2.9.8-h422b904_5                    conda-forge
    libxslt:          1.1.32-h88dbc4e_2                   conda-forge
    ncurses:          6.1-hfc679d8_1                      conda-forge
    nitro:            2.7.dev3-hfc679d8_0                 conda-forge
    numpy:            1.15.4-py36_blas_openblashb06ca3d_0 conda-forge [blas_openblas]
    openblas:         0.3.3-ha44fe06_1                    conda-forge
    openjpeg:         2.3.0-h0e734dc_3                    conda-forge
    openssl:          1.0.2p-h470a237_1                   conda-forge
    pcl:              1.8.1-h3a4cd21_2                    conda-forge
    pcre:             8.41-hfc679d8_3                     conda-forge
    pdal:             1.7.2-py36ha38bd43_2                conda-forge
    pixman:           0.34.0-h470a237_3                   conda-forge
    poppler:          0.61.1-3                            conda-forge
    poppler-data:     0.4.9-0                             conda-forge
    postgresql:       10.3-py36_0                         conda-forge
    proj4:            4.9.3-h470a237_8                    conda-forge
    pthread-stubs:    0.4-h470a237_1                      conda-forge
    python:           3.6.6-h5001a0f_3                    conda-forge
    readline:         7.0-haf1bffa_1                      conda-forge
    sqlite:           3.25.3-hb1c47c0_0                   conda-forge
    tk:               8.6.8-ha92aebf_0                    conda-forge
    xerces-c:         3.2.0-h5d6a6da_2                    conda-forge
    xorg-kbproto:     1.0.7-h470a237_2                    conda-forge
    xorg-libice:      1.0.9-h470a237_4                    conda-forge
    xorg-libsm:       1.2.2-h470a237_5                    conda-forge
    xorg-libx11:      1.6.6-h470a237_0                    conda-forge
    xorg-libxau:      1.0.8-h470a237_6                    conda-forge
    xorg-libxdmcp:    1.1.2-h470a237_7                    conda-forge
    xorg-libxext:     1.3.3-h470a237_4                    conda-forge
    xorg-libxrender:  0.9.10-h470a237_2                   conda-forge
    xorg-renderproto: 0.11.1-h470a237_2                   conda-forge
    xorg-xextproto:   7.3.0-h470a237_2                    conda-forge
    xorg-xproto:      7.0.31-h470a237_7                   conda-forge
    xz:               5.2.4-h470a237_1                    conda-forge
    zlib:             1.2.11-h470a237_3                   conda-forge

```

For Python 2.7 this is similar, For Python 3.7 there is `postgresql` blocking.

It might depend on the channels you have in your conda setup and which other packages you have inside.

**Comment by chambbj** [comment] 2018-11-12 12:33
@kmuehlbauer I don't recall if @hobu had documented this elsewhere, but I think this problem is specific to Windows.

On Windows, when running the command

```
conda create -n pdal01 -c conda-forge pdal
```

I get 

```
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.4
  latest version: 4.5.11

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: C:\Miniconda3\envs\pdal01

  added / updated specs:
    - pdal


The following NEW packages will be INSTALLED:

    blas:            1.0-mkl
    boost-cpp:       1.67.0-vc14_0         conda-forge [vc14]
    ca-certificates: 2018.10.15-ha4d7672_0 conda-forge
    cairo:           1.14.10-vc14_0        conda-forge [vc14]
    certifi:         2018.10.15-py36_1000  conda-forge
    curl:            7.62.0-h4496350_1000  conda-forge
    expat:           2.2.5-vc14_0          conda-forge [vc14]
    flann:           1.9.1-hacb3dfd_1003   conda-forge
    geos:            3.6.2-he025d50_3      conda-forge
    geotiff:         1.4.2-vc14_1          conda-forge [vc14]
    hdf5:            1.10.3-he51fdeb_1001  conda-forge
    hexer:           1.4.0-vc14_1          conda-forge [vc14]
    icc_rt:          2017.0.4-h97af966_0
    icu:             58.2-vc14_0           conda-forge [vc14]
    intel-openmp:    2019.0-118
    jpeg:            9b-vc14_2             conda-forge [vc14]
    jsoncpp:         1.8.1-vc14_0          conda-forge [vc14]
    krb5:            1.16.1-h038dc86_0     conda-forge
    laszip:          3.2.2-vc14_0          conda-forge [vc14]
    laz-perf:        1.2.0-vc14_1          conda-forge [vc14]
    libcurl:         7.62.0-h4496350_1000  conda-forge
    libgdal:         1.11.2-1
    libkml:          1.3.0-h6c56937_1008   conda-forge
    libpng:          1.6.34-vc14_0         conda-forge [vc14]
    libpq:           10.3-hc4dcbb0_0
    libssh2:         1.8.0-hc4dcbb0_2      conda-forge
    libtiff:         4.0.9-vc14_0          conda-forge [vc14]
    mkl:             2019.0-118
    mkl_fft:         1.0.6-py36_0          conda-forge
    mkl_random:      1.0.2-py36_0          conda-forge
    nitro:           2.7.dev2-vc14_0       conda-forge [vc14]
    numpy:           1.15.4-py36ha559c80_0
    numpy-base:      1.15.4-py36h8128ebf_0
    openssl:         1.0.2o-vc14_0         conda-forge [vc14]
    pcl:             1.8.1-h0a54bab_2      conda-forge
    pdal:            1.8.0-py36h3e93595_2  conda-forge
    pip:             18.1-py36_1000        conda-forge
    pixman:          0.34.0-vc14_2         conda-forge [vc14]
    postgresql:      10.3-hc4dcbb0_0
    proj4:           4.9.3-vc14_5          conda-forge [vc14]
    python:          3.6.6-he025d50_0      conda-forge
    setuptools:      40.5.0-py36_0         conda-forge
    sqlite:          3.25.3-hfa6e2cd_1000  conda-forge
    tk:              8.6.8-vc14_0          conda-forge [vc14]
    vc:              14-0                  conda-forge
    vs2015_runtime:  14.0.25420-0          conda-forge
    wheel:           0.32.2-py36_0         conda-forge
    wincertstore:    0.2-py36_1002         conda-forge
    zlib:            1.2.11-vc14_0         conda-forge [vc14]
```

To answer your question about Python, it's 3.6. You'll also notice libgdal 1.11.2 sneaking it's way in.

**Comment by ocefpaf** [comment] 2018-11-12 13:49
> To answer your question about Python, it's 3.6. You'll also notice libgdal 1.11.2 sneaking it's way in.

That is a bad mix of `defaults` and `conda-forge` there. If you can afford to remove `defaults` entirely (not always an option on Windows b/c `conda-forge` does not have `scipy`) than this would either be solved or at least we could know what packages may be the culprit in causing that.

**Comment by chambbj** [comment] 2018-11-12 13:59
@ocefpaf Thanks for the suggestion. I just removed `defaults` from my .condarc file and tried again. Unfortunately, I see no change. What output can I provide to help troubleshoot the offending package? Here is the list of packages it is trying to install without `defaults` (I think identical to the original list).

```
The following NEW packages will be INSTALLED:

    blas:            1.0-mkl
    boost-cpp:       1.67.0-vc14_0         conda-forge [vc14]
    ca-certificates: 2018.10.15-ha4d7672_0 conda-forge
    cairo:           1.14.10-vc14_0        conda-forge [vc14]
    certifi:         2018.10.15-py36_1000  conda-forge
    curl:            7.62.0-h4496350_1000  conda-forge
    expat:           2.2.5-vc14_0          conda-forge [vc14]
    flann:           1.9.1-hacb3dfd_1003   conda-forge
    geos:            3.6.2-he025d50_3      conda-forge
    geotiff:         1.4.2-vc14_1          conda-forge [vc14]
    hdf5:            1.10.3-he51fdeb_1001  conda-forge
    hexer:           1.4.0-vc14_1          conda-forge [vc14]
    icc_rt:          2017.0.4-h97af966_0
    icu:             58.2-vc14_0           conda-forge [vc14]
    intel-openmp:    2019.0-118
    jpeg:            9b-vc14_2             conda-forge [vc14]
    jsoncpp:         1.8.1-vc14_0          conda-forge [vc14]
    krb5:            1.16.1-h038dc86_0     conda-forge
    laszip:          3.2.2-vc14_0          conda-forge [vc14]
    laz-perf:        1.2.0-vc14_1          conda-forge [vc14]
    libcurl:         7.62.0-h4496350_1000  conda-forge
    libgdal:         1.11.2-1
    libkml:          1.3.0-h6c56937_1008   conda-forge
    libpng:          1.6.34-vc14_0         conda-forge [vc14]
    libpq:           10.3-hc4dcbb0_0
    libssh2:         1.8.0-hc4dcbb0_2      conda-forge
    libtiff:         4.0.9-vc14_0          conda-forge [vc14]
    mkl:             2019.0-118
    mkl_fft:         1.0.6-py36_0          conda-forge
    mkl_random:      1.0.2-py36_0          conda-forge
    nitro:           2.7.dev2-vc14_0       conda-forge [vc14]
    numpy:           1.15.4-py36ha559c80_0
    numpy-base:      1.15.4-py36h8128ebf_0
    openssl:         1.0.2o-vc14_0         conda-forge [vc14]
    pcl:             1.8.1-h0a54bab_2      conda-forge
    pdal:            1.8.0-py36h3e93595_2  conda-forge
    pip:             18.1-py36_1000        conda-forge
    pixman:          0.34.0-vc14_2         conda-forge [vc14]
    postgresql:      10.3-hc4dcbb0_0
    proj4:           4.9.3-vc14_5          conda-forge [vc14]
    python:          3.6.6-he025d50_0      conda-forge
    setuptools:      40.5.0-py36_0         conda-forge
    sqlite:          3.25.3-hfa6e2cd_1000  conda-forge
    tk:              8.6.8-vc14_0          conda-forge [vc14]
    vc:              14-0                  conda-forge
    vs2015_runtime:  14.0.25420-0          conda-forge
    wheel:           0.32.2-py36_0         conda-forge
    wincertstore:    0.2-py36_1002         conda-forge
    zlib:            1.2.11-vc14_0         conda-forge [vc14]
```

And from `conda info`:

```
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
```

**Comment by ocefpaf** [comment] 2018-11-12 14:01
> @ocefpaf Thanks for the suggestion. I just removed `defaults` from my .condarc file and tried again. Unfortunately, I see no change. What output can I provide to help troubleshoot the offending package? Here is the list of packages it is trying to install without `defaults` (I think identical to the original list).

You are still getting packages from `defaults` there, so unless there are multiple `.condarc`s and you did not get the right one I believe should file an issue upstream with `conda`.

**Comment by kmuehlbauer** [comment] 2018-11-12 14:06
@chambbj Seems that I can pull a `conda-forge` only env (even with defaults channel in `.condarc`)  by issuing:

```
conda create -n PDAL pdal lingdal numpy
```

**Comment by kmuehlbauer** [comment] 2018-11-12 14:30
Yes, this is a hack! IMHO it seems, that `numpy` gets channel precedence for `default` even if a fitting version is available in `conda-forge`. And this has serveral side-effects, as pulling in also other dependencies from `default`. But @ocefpaf might know better.

**Comment by hobu** [comment] 2018-11-12 14:33
> it seems, that `numpy` gets channel precedence for `default` even if a fitting version is available in `conda-forge`

Ah, so if we were to pin `numpy` to the version that exists in the `conda-forge` `libgdal`, we would get the expected behavior?

**Comment by ocefpaf** [comment] 2018-11-12 14:33
Yep. "Forcing" conda's had by adding more package to the solver in one go helps. But that is a hack IMO b/c there should be no preference for a package from `defaults` if you explicitly remove it. Thanks for opening an issue upstream.

**Comment by ocefpaf** [comment] 2018-11-30 10:12
@hobu closing this b/c it seems you can fix it with a in in pdal, right? If not please re-open.

**Closed by ocefpaf** 2018-11-30 10:12 UTC
